'use strict';
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{chromium}=require('playwright');
const C=require('../src/core'),{fixture}=require('./helpers');const root=path.resolve(__dirname,'..'),bundle=JSON.parse(fs.readFileSync(path.join(root,'branch_story_tavern_helper_import.json'))).content,requests=[],errors=[];
const p=C.normalizeProject({id:'ui_new',title:'阳台故事',actors:[{id:'wang',name:'小王'}],variables:[{id:'aff',title:'好感',owner:'wang',type:'number',default:30}],collections:[{id:'key',title:'房卡',description:'阳台交谈后取得的房卡'}],nodes:[{id:'a',title:'阳台交谈',guidance:'演绎阳台内的互动',completion_criteria:'实际离开阳台',completion_action:{label:'离开阳台',action_text:'我离开阳台'},effects:[{collect:'key'}],routes:[{target:'b',label:'探查密室',condition:{collected:'key'}}]},{id:'b',title:'密室',guidance:'演绎密室内的调查',routes:[],effects:[]}],events:[{id:'gift',title:'赠花',description:'小王实际接受花',actor_id:'player',recipient_id:'wang',repeat_policy:'once_per_accepted_turn',auto_settle:true,effects:[{add:{variable:'aff',value:1}}]}]});
const source='你走进阳台，小王正在栏杆旁。\n你递给他一张房卡。\n他将房卡收好。\n你离开了阳台。';
const extracted={title:'阳台分析',collections:[{id:'key',title:'房卡',evidence:'你递给他一张房卡。'}],nodes:[{id:'n',title:'阳台',detail:source,guidance:'当前阳台互动',completion_criteria:'交付房卡并离开',completion_action:{label:'离开阳台',action_text:'我离开阳台'},completion_evidence:'他将房卡收好。……你离开了阳台。',result_ids:['key'],routes:[]}]};
const server=http.createServer(async(req,res)=>{
 if(req.url==='/bundle.js'){res.setHeader('Content-Type','text/javascript');res.end(bundle);return;}
 if(req.url==='/frame'){res.setHeader('Content-Type','text/html');res.end('<script src="/bundle.js"></script>');return;}
 if(req.url==='/v1/chat/completions'){
  const chunks=[];for await(const chunk of req)chunks.push(chunk);const body=JSON.parse(Buffer.concat(chunks)),input=JSON.parse(body.messages[1].content);requests.push({body,input});let value;
  if(input.operation==='review_chunk' || input.operation==='review_playability' || input.operation==='review_script')value={complete:true,issues:[]};
  else if(input.check_id)value={complete:true,check_id:input.check_id,results:input.candidates.map(c=>({key:c.key,status:'completed',evidence:[{message_id:input.dialogues.flat().find(m=>m.role==='assistant' && m.text.includes('你离开了阳台。')).message_id,quote:'你离开了阳台。'}]}))};
  else value=extracted;
  res.setHeader('Content-Type','application/json');res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}]}));return;
 }
 const fixtureText=fixture.toString().replace('host: new Host(root)','host:null');
 res.setHeader('Content-Type','text/html; charset=utf-8');res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#222;color:white}iframe{display:none}#sheld{height:100dvh;display:flex;flex-direction:column}#chat{flex:1;overflow:auto}#send_form{flex:none}textarea{width:95%;height:44px}</style><div id="sheld"><div id="chat"><span id="live" data-bse-variable="aff">999</span></div><form id="send_form"><textarea id="send_textarea"></textarea></form></div><script>const C={clone:x=>JSON.parse(JSON.stringify(x))};const fixture=${fixtureText};window.testHost=fixture();let card={avatar:'a.png',name:'当前测试卡'};testHost.root.SillyTavern={getContext:()=>({characterId:0,characters:[card]})};testHost.storage.script.branch_story_settings={runtime_mode:'companion',profile:{auto_partition:false,author_review:true},project_id:'ui_new',drafts:{ui_new:${JSON.stringify(p)}}};window.TavernHelper=testHost.root;window.sendRound=async(body,items={},format="legacy",playerInput="自主行动")=>{const e=document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine,h=testHost.root,u=h.messages.length;h.messages.push({message_id:u,role:'user',message:playerInput});await e.prepareTurn(u);const a=h.messages.length,report={turn:e.state.companion.turn.id,complete:true,stages:[],events:[],present:['wang'],...items};h.messages.push({message_id:a,role:'assistant',message:body+'\\n'+(format==='canonical'?'<!--BSE_REPORT '+JSON.stringify(report)+' -->':'<!--<bse-report>'+JSON.stringify(report)+'-->')+'\\n<tse_meta target="wang"><player_mind>普通状态记录</player_mind></tse_meta>'});const div=document.createElement('div');div.className='mes';div.dataset.messageId=a;div.textContent=body;const meta=document.createElement('bse-report');meta.textContent=JSON.stringify(report);div.append(meta);const value=document.createElement('span');value.dataset.bseVariable='aff';value.className='historic';value.textContent='999';div.append(value);document.querySelector('#chat').append(div);await e.captureDraft(a);await e.processCompanion();return a;};window.switchCard=()=>{card={avatar:'b.png',name:'第二张卡'};document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.bindChat();};const frame=document.createElement('iframe');frame.src='/frame';document.body.append(frame);</script>`);
});
const evaluate=(page,fn)=>page.evaluate(fn);
async function run(){await new Promise(r=>server.listen(0,'127.0.0.1',r));const browser=await chromium.launch({headless:true,executablePath:process.env.BSE_CHROMIUM || '/usr/bin/chromium',args:['--no-sandbox']});try{for(const width of [1366,390,320]){
 const ctx=await browser.newContext({viewport:{width,height:900},isMobile:width<700,hasTouch:width<700}),page=await ctx.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_startup__?.status==='ready');await page.locator('.launcher').click();assert((await page.locator('.project-switcher').innerText()).includes('当前测试卡'));
 await evaluate(page,async()=>{const e=document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine;await e.updateSettings({enabled:true,quick_options:true,profile:{base_url:location.origin+'/v1',model:'mock'}});});await page.locator('[data-action="close"]').click();assert.equal(await page.locator('.bse-choice').innerText(),'离开阳台');await page.locator('.bse-choice').click();assert.equal(await page.locator('textarea').inputValue(),'我离开阳台');assert.equal(await evaluate(page,()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.state.collected_ids.length),0);
 const before=requests.length;const first=await evaluate(page,()=>sendRound('小王接过了花。',{events:[{id:'gift',status:'completed',quote:'小王接过了花。',actor_id:'player',recipient_id:'wang'}]}));assert.equal(requests.length,before);await page.waitForFunction(()=>document.querySelector('#live').textContent==='31');assert.equal(await page.locator('.historic').first().innerText(),'31');assert.equal(await page.locator('bse-report').first().isVisible(),false);
 await evaluate(page,()=>sendRound('小王接过了花。',{events:[{id:'gift',status:'completed',quote:'小王接过了花。',actor_id:'player',recipient_id:'wang'}]},'canonical'));await page.waitForFunction(()=>document.querySelector('#live').textContent==='32');assert.equal(await page.locator('.historic').first().innerText(),'31');
 await evaluate(page,async()=>{await document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.updateSettings({profile:{base_url:'',model:''}});});
 await evaluate(page,()=>sendRound('你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]}));assert.equal(requests.length,before);await page.locator('.launcher').click();await page.locator('[data-action="tab"][data-tab="records"]').click();assert((await page.locator('main').innerText()).includes('辅助 API 未配置'));assert(!(await page.locator('main').innerText()).includes('等待行动与回复'));assert((await page.locator('main').innerText()).includes('格式恢复'));await evaluate(page,async()=>{await document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.updateSettings({profile:{base_url:location.origin+'/v1',model:'mock'}});});await page.locator('[data-action="companion-retry"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.state.collected_ids.includes('key'));await page.locator('[data-action="close"]').click();assert.equal(requests.length-before,1);assert.equal(await page.locator('.bse-choice').innerText(),'探查密室');assert.equal(await page.locator('.historic').first().innerText(),'31');
 await evaluate(page,()=>sendRound('你来到密室门口。',{stages:[{id:'b',status:'completed',quote:'你来到密室门口。'}],choice:{target:'b',source:'user',quote:'我去看看那间密室'}},'canonical','我去看看那间密室'));assert.equal(await evaluate(page,()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.state.current_node_id),'b');assert.equal(await evaluate(page,()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.state.completed_node_ids.includes('b')),false);assert.equal(requests.length-before,1);
 await page.locator('.launcher').click();await page.locator('[data-action="tab"][data-tab="analysis"]').click();assert((await page.locator('.analysis-cost').innerText()).includes('调用预估'));await page.locator('[name="analysis_text"]').fill(source);await page.locator('.analysis-prompts').evaluate(el=>el.open=true);await page.locator('[name="playability_prompt"]').fill('自定义可游玩性复核');await page.locator('[data-action="analysis-prompts-save"]').click();const authorBefore=requests.length;await page.locator('[data-action="analysis-run"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.analysisDraft?.author_review?.complete);assert.equal(requests.length-authorBefore,4);assert.equal(requests[authorBefore+2].body.messages[0].content,'自定义可游玩性复核');assert.equal(await evaluate(page,()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.analysisDraft.evidence_repairs.length),1);assert((await page.locator('.analysis-conversion').innerText()).includes('转化为剧本'));
 const reviseBefore=requests.length;await page.locator('[data-action="analysis-revise"]').first().click();assert.equal(requests.length,reviseBefore);assert.equal(await page.locator('[name="analysis_text"]').inputValue(),source);assert((await page.locator('[name="analysis_wish"]').inputValue()).includes('复核问题'));
 page.once('dialog',d=>d.accept());await page.locator('[data-action="analysis-convert"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.title==='阳台分析');assert.equal(requests.length-authorBefore,4);assert.equal(await evaluate(page,()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.nodes[0].completion_action.label),'离开阳台');
 await evaluate(page,()=>switchCard());await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.card.name==='第二张卡');assert((await page.locator('.project-switcher').innerText()).includes('第二张卡'));assert(!(await page.locator('[name="project_switch"]').innerText()).includes('阳台分析'));const overflow=await page.locator('.panel').evaluate(el=>el.scrollWidth>el.clientWidth+1);assert(!overflow);
 fs.mkdirSync(path.join(root,'artifacts'),{recursive:true});await page.screenshot({path:path.join(root,'artifacts','companion-'+width+'.png')});console.log(width+'px：角色卡库隔离、自然结束行动、零API赠礼、状态栏快照/回报隐藏、新旧报告/TSE兼容、自由输入/越界完成不吞选择、可游玩提示词保存/带问题重析、缺API明确提示/按钮恢复、关键集中核验及四步作者分析复核通过');await ctx.close();
}assert.deepEqual(errors,[]);}finally{await browser.close();server.close();}}
run().catch(e=>{console.error(e);process.exitCode=1;});
