'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const C=require('../src/core'),R=require('../src/companion'),A=require('../src/api'),{Engine}=require('../src/engine'),{fixture,mockClient,deferred,tick}=require('./helpers');
const project=()=>C.normalizeProject({id:'balcony',title:'阳台互动',actors:[{id:'wang',name:'小王',aliases:['王先生']}],variables:[{id:'aff',title:'好感',owner:'wang',type:'number',default:30,min:0,max:100}],collections:[{id:'key',title:'房卡'}],nodes:[{id:'a',title:'阳台',guidance:'仅演绎阳台',completion_criteria:'正文实际离开阳台',completion_action:{label:'离开阳台',action_text:'我离开阳台',intent:'实际离开'},effects:[{collect:'key'}],routes:[{target:'b',label:'探查密室',condition:{collected:'key'}}]},{id:'b',title:'密室',guidance:'密室内的线索',routes:[],effects:[]}],events:[{id:'gift',title:'赠礼',description:'小王接受赠礼',completion_criteria:'实际交付且接受',actor_id:'player',recipient_id:'wang',repeat_policy:'once_per_accepted_turn',auto_settle:true,effects:[{add:{variable:'aff',value:1,max:70}}]}]});
async function setup(client=mockClient(),p=project()) {const f=fixture();f.storage.script.branch_story_settings.runtime_mode='companion';const e=new Engine(f.host,client);await e.init();await e.setProject(p);await e.updateSettings({enabled:true,runtime_mode:'companion'});return {...f,e,client};}
async function round(f,body,items={},auto=true,input='自由行动') {const u=f.root.messages.length;f.root.messages.push({message_id:u,role:'user',message:input});await f.e.prepareTurn(u);const report={turn:R.init(f.e.state).turn.id,complete:true,stages:[],events:[],present:[],...items};const a=f.root.messages.length;f.root.messages.push({message_id:a,role:'assistant',message:body+'\n<bse-report>'+JSON.stringify(report)+'</bse-report>'});await f.e.captureDraft(a);await f.e.processCompanion(auto);return a;}
const accepted={id:'gift',status:'completed',actor_id:'player',recipient_id:'wang',quote:'小王接过了花。'};
test('普通事件零额外API、本地奖励与去重，状态栏读取结算后快照',async()=>{const f=await setup();let calls=0;f.client.detect=async()=>{calls++;throw Error('不应请求');};const id=await round(f,'小王接过了花。',{events:[accepted],present:['wang','unknown']});assert.equal(f.e.state.variables.aff,31);assert.equal(calls,0);assert.equal(f.e.state.companion.message_snapshots[id].variables.aff,31);assert.deepEqual(f.e.state.companion.present,['wang']);await f.e.processCompanion();assert.equal(f.e.state.variables.aff,31);f.e.destroy();});
test('自然结束按钮只填行动，关键阶段主模型成功也不直接取得房卡或打开B',async()=>{const f=await setup();assert.equal(f.e.quickRoutes()[0].label,'离开阳台');const before=f.e.state.current_node_id,text=f.e.stageChoice('complete:a');assert.equal(text,'我离开阳台');assert.equal(f.e.state.current_node_id,before);await round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]},false,text);assert.deepEqual(f.e.state.collected_ids,[]);assert(!f.e.quickRoutes().some(x=>x.target==='b'));assert.equal(f.e.state.companion.queue.length,1);f.e.destroy();});
test('自主输入不调用分支识别API，阶段集中复核成功后才开放后续',async()=>{const f=await setup();let calls=0;f.client.choose=()=>{throw Error('不应识别自由输入');};f.client.checkpoint=async(p,c)=>{calls++;return c.map(x=>({key:x.key,status:'completed',evidence:x.source.evidence}));};await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});await round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]},true,'我返回客厅');assert.equal(calls,1);assert.deepEqual(f.e.state.collected_ids,['key']);assert.equal(f.e.quickRoutes()[0].target,'b');f.e.destroy();});
test('复核否决不倒带或修改正文，保持当前阶段并允许继续行动',async()=>{const f=await setup();f.client.checkpoint=async(p,c)=>c.map(x=>({key:x.key,status:'rejected',evidence:[]}));await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});const id=await round(f,'你只是望向出口。',{stages:[{id:'a',status:'completed',quote:'你只是望向出口。'}]});assert.equal(f.e.state.current_node_id,'a');assert.deepEqual(f.e.state.collected_ids,[]);assert(f.root.messages.find(m=>m.message_id===id).message.includes('你只是望向出口。'));assert.equal(f.e.state.companion.queue.length,0);f.e.destroy();});
test('集中核验失败最多三次重试，完整性错误不会误放行',async()=>{const f=await setup();let calls=0;f.client.checkpoint=async()=>{calls++;throw Error('半截JSON');};await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});await round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});assert.equal(calls,4);assert.equal(f.e.state.collected_ids.length,0);assert.equal(f.e.state.companion.queue.length,1);assert(!f.e.state.paused);f.e.destroy();});
test('待定赠礼下一轮完成沿用同一次尝试，不发重复奖励',async()=>{const f=await setup();await round(f,'小王犹豫着。',{events:[{...accepted,status:'uncertain',quote:'小王犹豫着。'}]},false);const attempt=Object.keys(f.e.state.companion.attempts)[0];await round(f,'小王接过了花。',{events:[{...accepted,attempt}]},false);assert.equal(f.e.state.variables.aff,31);assert.equal(f.e.state.event_counts.gift,1);assert.equal(Object.keys(f.e.state.companion.attempts).length,1);assert.equal(f.e.state.companion.queue.length,0);f.e.destroy();});
test('主体不符、未知ID、引用回报自身及截断标记都不能结算',async()=>{for(const event of [{...accepted,recipient_id:'other'},{...accepted,id:'unknown'},{...accepted,quote:'不存在的原句'}]){const f=await setup();await round(f,'小王接过了花。',{events:[event]},false);assert.equal(f.e.state.variables.aff,30);f.e.destroy();}assert.throws(()=>R.parse('正文<bse-report>{"complete":true}',{turn:'x'}),/截断/);assert.throws(()=>R.parse('正文<bse-report>{"turn":"old","complete":true}</bse-report>',{turn:'new'}),/标识/);});
test('数值被用于任何解锁门槛时自动转为关键，普通设置不能绕过',async()=>{const p=project();p.nodes[0].routes[0].condition={variable:{id:'aff',op:'gte',value:31}};const f=await setup(mockClient(),p);await round(f,'小王接过了花。',{events:[accepted]},false);assert.equal(f.e.state.variables.aff,30);assert.equal(f.e.state.companion.queue.length,1);f.e.destroy();});
test('同一阶段普通互动按三回合节奏集中核验待定事件',async()=>{const f=await setup();let calls=0;f.client.checkpoint=async(p,c)=>{calls++;return c.map(x=>({key:x.key,status:'uncertain',evidence:[]}));};await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});await round(f,'小王犹豫着。',{events:[{...accepted,status:'uncertain',quote:'小王犹豫着。'}]});assert.equal(calls,0);await round(f,'他仍在考虑。');assert.equal(calls,0);await round(f,'夜风吹过。');assert.equal(calls,1);f.e.destroy();});
test('核验进行时普通互动不等待，配置或聊天切换丢弃晚到结果',async()=>{const f=await setup(),gate=deferred(),started=deferred();f.client.checkpoint=async(p,c)=>{started.resolve();await gate.promise;return c.map(x=>({key:x.key,status:'completed',evidence:x.source.evidence}));};await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});const job=round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});await started.promise;const uid=f.root.messages.length;f.root.messages.push({message_id:uid,role:'user',message:'我看看天空。'});await Promise.race([f.e.prepareTurn(uid),new Promise((r,j)=>setTimeout(()=>j(Error('普通行动不应等待核验')),100))]);f.root.chat='other';f.e.bindChat();gate.resolve();await job;assert.equal(f.e.state.collected_ids.length,0);f.e.destroy();});
test('角色卡按avatar稳定隔离，同名卡、旧请求和新聊天进度不会混合',async()=>{const f=fixture();let card={avatar:'a.png',name:'同名'};f.root.SillyTavern={getContext:()=>({characterId:0,characters:[card]})};f.storage.script.branch_story_settings.runtime_mode='companion';const e=new Engine(f.host);await e.init();const a=e.project.id;await e.createProject('A专属');const aa=e.project.id;card={avatar:'b.png',name:'同名'};e.bindChat();assert.equal(e.card.id,'card:b.png');assert(!e.projectList().some(p=>p.id===aa));await assert.rejects(e.switchProject(aa),/角色卡/);const b=e.project.id;card={avatar:'a.png',name:'改名'};e.bindChat();assert.equal(e.project.id,aa);assert.equal(e.card.name,'改名');assert(!e.projectList().some(p=>p.id===b));assert(e.projectList().some(p=>p.id===a));e.destroy();});
test('真实API集中核验必须返回全部候选及请求标识，回报正文不作为证据',async()=>{const item={key:'event:gift:x',source:{assistant_id:1},dialogue:[{role:'assistant',message_id:'1',text:'小王拒绝了。<bse-report>{"quote":"小王接过了花。"}</bse-report>'}]},defs=[{key:item.key,id:'gift',actor_id:'player',recipient_id:'wang'}];let wrong=false;const api=new A.Client(async(url,opt)=>{const payload=JSON.parse(JSON.parse(opt.body).messages[1].content);return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({complete:true,check_id:wrong?'wrong':payload.check_id,results:[{key:item.key,status:'completed',actor_id:'player',recipient_id:'wang',evidence:[{message_id:'1',quote:'小王接过了花。'}]}]})}}]})};});const profile={base_url:'https://mock.test',model:'mock'};assert.equal((await api.checkpoint(profile,[item],defs,{}))[0].status,'uncertain');wrong=true;await assert.rejects(api.checkpoint(profile,[item],defs,{}),/不完整/);});
test('隐藏回报注释必须完整关闭，未知在场角色不得跨候选注入',async()=>{const f=await setup();const expected={turn:'t',stages:[],events:[]},json=JSON.stringify({turn:'t',complete:true,stages:[],events:[]});assert.throws(()=>R.parse('正文<!--<bse-report>'+json+'</bse-report>',expected),/未完整关闭/);assert.equal(R.parse('正文<!--<bse-report>'+json+'</bse-report>-->',expected).body,'正文');await round(f,'普通交谈。',{present:['wang','future']});assert(!R.init(f.e.state).present.includes('future'));f.e.destroy();});
test('影响另一个事件前置数值的奖励也先核验，不能以普通级别绕过',()=>{const p=project();p.events.push({id:'next',condition:{variable:{id:'aff',op:'gte',value:50}}});assert.equal(R.critical(p,'event','gift'),true);});
test('关闭自动结算的已核验关键结果保留，作者确认一次后开启依赖',async()=>{const client=mockClient();client.checkpoint=async(profile,items)=>items.map(x=>({key:x.key,status:'completed',evidence:x.source.evidence}));const p=project();p.nodes.find(n=>n.id==='a').auto_complete=false;const f=await setup(client,p);await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});await round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});assert.equal(R.init(f.e.state).queue[0].status,'verified');assert(!f.e.state.collected_ids.includes('key'));f.e.confirmCandidate('stage:a');assert(f.e.state.collected_ids.includes('key'));assert.equal(R.init(f.e.state).queue.length,0);assert.throws(()=>f.e.confirmCandidate('stage:a'),/尚未核验/);f.e.destroy();});

const tseMeta='<tse_meta x="-0.3" target="wang"><player_mind>小王接过了花。</player_mind></tse_meta>';
test('新简短注释及旧标签均可读取，完整JSON缺旧尾标签与TSE共存仅恢复格式',()=>{
  const expected={turn:'t',stages:[],events:[{id:'gift',actor_id:'player',recipient_id:'wang'}]},json=JSON.stringify({turn:'t',complete:true,events:[accepted]});
  for(const envelope of ['<!--BSE_REPORT '+json+' -->','<!--<bse-report>'+json+'</bse-report>-->','<bse-report>'+json+'</bse-report>','<!--<bse-report>'+json+'-->']){
    const r=R.parse('小王接过了花。\n'+envelope+'\n'+tseMeta,expected);assert.equal(r.events[0].status,'completed');assert(!r.body.includes('player_mind'));assert.equal(Boolean(r.repair),envelope.endsWith(json+'-->'));
  }
});
test('半截JSON、半截注释/TSE、额外正文、重复报告、错误回合均不被格式恢复放行',()=>{
  const expected={turn:'t',stages:[],events:[]},json=JSON.stringify({turn:'t',complete:true}),valid='<!--BSE_REPORT '+json+' -->';
  for(const text of ['<!--BSE_REPORT '+json,'<!--<bse-report>'+json,'<!--<bse-report>'+json.slice(0,-1)+'-->','<!--BSE_REPORT '+json.slice(0,-1)+' -->',valid+'<tse_meta>half',valid+'后来你离开了。',valid+valid,valid+'<bse-report>half',valid.replace('"t"','"old"')])assert.throws(()=>R.parse('正文'+text,expected));
});
test('TSE元数据中的文字不能冒充主模型或辅助核验证据，不合并两侧正文',async()=>{
  const expected={turn:'t',stages:[],events:[{id:'gift'}]},json=JSON.stringify({turn:'t',complete:true,events:[accepted]});
  const r=R.parse('他只是看着你。'+tseMeta+'<!--BSE_REPORT '+json+' -->',expected);assert.equal(r.events[0].status,'uncertain');
  const split=R.parse('小王'+tseMeta+'接过了花。<!--BSE_REPORT '+json+' -->',expected);assert.equal(split.events[0].status,'uncertain');
  const item={key:'event:gift:x',source:{assistant_id:1},dialogue:[{role:'assistant',message_id:'1',text:'他只是看着你。<!--<bse-report>'+json+'-->'+tseMeta}]};
  const api=new A.Client(async(url,opt)=>{const payload=JSON.parse(JSON.parse(opt.body).messages[1].content);assert(!payload.dialogues[0][0].text.includes('小王接过了花。'));return {ok:true,json:async()=>({choices:[{finish_reason:'stop',message:{content:JSON.stringify({complete:true,check_id:payload.check_id,results:[{key:item.key,status:'completed',evidence:[{message_id:'1',quote:'小王接过了花。'}]}]})}}]})};});
  assert.equal((await api.checkpoint({base_url:'https://mock.test',model:'mock'},[item],[{key:item.key}],{}))[0].status,'uncertain');
});
async function screenshotRound(f,items,body='你离开了阳台。'){
  const u=f.root.messages.length;f.root.messages.push({message_id:u,role:'user',message:'我离开阳台'});await f.e.prepareTurn(u);
  const json=JSON.stringify({turn:f.e.state.companion.turn.id,complete:true,stages:[],events:[],...items}),a=f.root.messages.length;
  f.root.messages.push({message_id:a,role:'assistant',message:body+'\n<!--<bse-report>'+json+'-->\n'+tseMeta});await f.e.captureDraft(a);return a;
}
test('截图格式的普通阶段本地完成并更新后续、记录、图，不增加API',async()=>{
  const p=project();p.nodes[0].effects=[];p.collections=[];p.nodes[0].routes[0].condition=true;const f=await setup(mockClient(),p);
  await screenshotRound(f,{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});await f.e.processCompanion();
  assert.deepEqual(f.e.state.completed_node_ids,['a']);assert.equal(f.e.quickRoutes()[0].target,'b');assert.equal(f.e.state.companion.queue.length,0);assert.match(f.e.state.companion.latest_report.message,/格式恢复/);
  assert.equal(require('../src/graph').build(f.e.project,f.e.state).nodes.find(n=>n.id==='node:a').status,'done');f.e.destroy();
});
test('旧版拒绝的同轮报告可手动重读，奖励只结算一次，不增加回合数',async()=>{
  const f=await setup();await screenshotRound(f,{events:[accepted]},'小王接过了花。');await f.e.processCompanion();
  const q=f.e.state.companion,key=Object.keys(q.reports)[0];assert.equal(f.e.state.variables.aff,31);
  q.reports[key]=true;q.logs=q.logs.filter(x=>x.kind!=='settled' && !x.kind.startsWith('report_'));q.logs.push({kind:'report_invalid',assistant_id:f.e.draft.assistant_id,message:'旧格式失败'});delete q.latest_report;
  await f.e.checkRound();await f.e.checkRound();assert.equal(f.e.state.variables.aff,31);assert.equal(f.e.state.event_counts.gift,1);assert.equal(f.e.state.companion.round,1);assert.equal(f.e.state.companion.reports[key],'accepted');f.e.destroy();
});
test('关键阶段缺API显示明确原因，图与行动均保持入口关闭，配置后核验恢复',async()=>{
  const f=await setup();await screenshotRound(f,{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});await f.e.processCompanion();
  assert.match(f.e.state.companion.checkpoint_status.message,/未配置/);assert.equal(f.e.state.collected_ids.length,0);assert.equal(f.e.state.completed_node_ids.length,0);
  assert.equal(require('../src/graph').build(f.e.project,f.e.state).nodes.find(n=>n.id==='node:b').status,'locked');
  f.client.checkpoint=async(p,c)=>c.map(x=>({key:x.key,status:'completed',evidence:x.source.evidence}));await f.e.updateSettings({profile:{base_url:'https://mock.test',model:'mock'}});await f.e.checkRound();
  assert.deepEqual(f.e.state.collected_ids,['key']);assert.equal(f.e.quickRoutes()[0].target,'b');assert.equal(f.e.state.companion.checkpoint_status.status,'done');f.e.destroy();
});
test('旧默认短报告提示词精确迁移，自定义提示词保留',async()=>{
  for(const old of [R.PREVIOUS_PROMPT,'作者自定义报告格式']){const f=fixture();f.storage.script.branch_story_settings.companion_prompt=old;const e=new Engine(f.host,mockClient());await e.init();assert.equal(e.settings.companion_prompt,old===R.PREVIOUS_PROMPT?R.PROMPT:old);e.destroy();}
});
test('格式失败重读后恢复进行中，移除同来源的占位候选，格式仍错保持原因',async()=>{
  const f=await setup();const a=await screenshotRound(f,{stages:[{id:'a',status:'in_progress',quote:'你仍在阳台上。'}]},'你仍在阳台上。');
  const parse=R.parse;R.parse=()=>{throw Error('旧版解析错误');};try{await f.e.processCompanion(false);}finally{R.parse=parse;}
  assert.equal(f.e.state.companion.queue.length,1);assert.equal(f.e.state.companion.latest_report.status,'invalid');await f.e.checkRound();assert.equal(f.e.state.companion.queue.length,0);assert.equal(f.e.state.companion.latest_report.status,'accepted');assert.equal(f.e.state.companion.round,1);
  f.root.messages.find(m=>m.message_id===a).message+='后来走入密室。';await f.e.captureDraft(a);await f.e.processCompanion(false);assert.equal(f.e.state.companion.latest_report.status,'invalid');assert.match(f.e.state.companion.latest_report.message,/含正文/);assert.equal(f.e.state.collected_ids.length,0);f.e.destroy();
});
test('自由跟踪合法进入下一阶段，越界完成项不吞选择、不发新阶段结果、零辅助API',async()=>{
  const p=project();p.nodes[0].effects=[];p.nodes[0].routes[0].condition=true;p.nodes[1].completion_criteria='老人收走账册';p.nodes[1].effects=[{collect:'key'}];
  const f=await setup(mockClient(),p);await round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});
  await round(f,'目标停在报刊亭前。',{stages:[{id:'b',status:'completed',quote:'目标停在报刊亭前。'}],choice:{target:'b',source:'user',quote:'继续跟上'}},true,'继续跟上');
  assert.equal(f.e.state.current_node_id,'b');assert.deepEqual(f.e.state.completed_node_ids,['a']);assert.deepEqual(f.e.state.collected_ids,[]);assert.equal(f.e.state.companion.queue.length,0);assert.match(f.e.state.companion.latest_report.warnings[0],/越界/);assert.equal(f.e.quickRoutes()[0].target,'complete:b');f.e.destroy();
});
test('重复/坏阶段项和错误事件项独立忽略，普通有效事件仍结算；重复同ID不择一放行',()=>{
  const expected={turn:'t',stages:[{id:'a'}],events:[{id:'gift',actor_id:'player',recipient_id:'wang'}],routes:[]},raw={turn:'t',complete:true,stages:[{id:'a',status:'completed',quote:'小王接过了花。'},{id:'a',status:'uncertain'},null],events:[{id:'fake',status:'completed'},accepted]};
  const r=R.parse('小王接过了花。<!--BSE_REPORT '+JSON.stringify(raw)+' -->',expected);assert.equal(r.stages.length,0);assert.equal(r.events.length,1);assert.equal(r.events[0].status,'completed');assert.equal(r.warnings.length,4);
});
test('玩家输入只证明入口选择，不能成为完成/领奖依据；未知入口与错误turn不放行',()=>{
  const expected={turn:'t',player_input:'我进入密室',stages:[{id:'a'}],events:[],routes:[{target:'b'}]},raw={turn:'t',complete:true,stages:[{id:'a',status:'completed',quote:'我进入密室'}],choice:{target:'b',source:'user',quote:'我进入密室'}};
  const encode=x=>'正文只有风声。<!--BSE_REPORT '+JSON.stringify(x)+' -->';let r=R.parse(encode(raw),expected);assert.equal(r.stages[0].status,'uncertain');assert.equal(r.choice.target,'b');r=R.parse(encode({...raw,choice:{...raw.choice,target:'c'}}),expected);assert.equal(r.choice,null);assert.throws(()=>R.parse(encode({...raw,turn:'造的turn'}),expected),/标识/);
});
test('进入选择仍遵守本地结果门槛，报告部分出错不把锁住路线当合法',async()=>{
  const f=await setup();await round(f,'小王站在阳台。',{stages:[{id:'b',status:'completed',quote:'小王站在阳台。'}],choice:{target:'b',source:'user',quote:'进入密室'}},true,'进入密室');assert.equal(f.e.state.current_node_id,'a');assert.deepEqual(f.e.state.collected_ids,[]);assert.deepEqual(f.e.state.completed_node_ids,[]);f.e.destroy();
});
test('输入被编辑后不能用注入时的旧选择证据推进',async()=>{
  const p=project();p.nodes[0].effects=[];p.nodes[0].routes[0].condition=true;p.collections=[];const f=await setup(mockClient(),p);await round(f,'你离开了阳台。',{stages:[{id:'a',status:'completed',quote:'你离开了阳台。'}]});
  const u=f.root.messages.length;f.root.messages.push({message_id:u,role:'user',message:'我要去看看那间密室'});await f.e.prepareTurn(u);const turn=f.e.state.companion.turn.id;f.root.messages.find(m=>m.message_id===u).message='我留在原地';const a=f.root.messages.length;f.root.messages.push({message_id:a,role:'assistant',message:'风声。<!--BSE_REPORT '+JSON.stringify({turn,complete:true,stages:[],events:[],choice:{target:'b',source:'user',quote:'我要去看看那间密室'}})+' -->'});await f.e.captureDraft(a);await f.e.processCompanion();assert.equal(f.e.state.current_node_id,'a');assert.equal(f.e.state.companion.logs.at(-1).kind,'stale');f.e.destroy();
});
