'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const A=require('../src/api'),C=require('../src/core'),{Engine,defaults}=require('../src/engine'),{fixture}=require('./helpers');
const original='信封里是一张临时访客凭证。\n他等脚步声过去。\n我拿起门卡。\n我抽出带缺口的原件。\n我携带原件退出书房。';
const raw=()=>({title:'证据测试',collections:[{id:'card',title:'门卡',evidence:'我拿起门卡。'}],nodes:[{id:'n1',title:'获取凭证与门卡',detail:original,guidance:'调查当前房间',completion_criteria:'取得门卡',completion_evidence:'信封里是一张临时访客凭证。……我拿起门卡。',result_ids:['card'],routes:[{target:'n2',label:'带原件撤出',condition:{collected:'card'},condition_evidence:'我抽出带缺口的原件。……我携带原件退出书房。'}]},{id:'n2',title:'取出原件',detail:'我抽出带缺口的原件。',guidance:'取出原件',completion_criteria:'取得原件',completion_evidence:'我拿起门卡。……我抽出带缺口的原件。',routes:[]}]});
const profile={...defaults().profile,base_url:'https://mock.test',model:'extract',auto_partition:false,author_review:false};
function mock(fn){const sent=[];const api=new A.Client(async(url,opt)=>{const body=JSON.parse(opt.body),input=JSON.parse(body.messages[1].content);sent.push({body,input});const value=await fn(input,body);return {ok:true,json:async()=>({choices:[{finish_reason:value.finish || 'stop',message:{content:JSON.stringify(value.data || value)}}]})};});return {api,sent};}
test('三处省略号拼接逐条精确恢复，完成与解锁依据均保留、零API',()=>{const draft=new A.Client().restoreAnalysis(original,raw());assert.equal(draft.request_count,0);assert.equal(draft.evidence_repairs.length,3);assert.equal(draft.project.nodes[0].completion_evidence.length,2);assert.deepEqual(draft.project.nodes[0].routes[0].condition,{collected:'card'});assert.equal(draft.project.nodes[0].routes[0].condition_evidence.length,2);assert.deepEqual(draft.project.nodes[0].effects,[{collect:'card'}]);});
test('原文自身含省略号保持连续引用，不误拆；改字/半空/超8引用不能放行',()=>{const text='她沉默了……终于接过门卡。',p=raw();p.nodes=p.nodes.slice(0,1);p.nodes[0].routes=[];p.nodes[0].detail=text;p.nodes[0].completion_evidence=text;p.collections[0].evidence=text;const d=new A.Client().restoreAnalysis(text,p);assert.equal(d.evidence_repairs.length,0);assert.equal(d.project.nodes[0].completion_evidence,text);for(const quote of ['我拿起门卡。……我拿起不存在的钥匙。',[],Array(9).fill('我拿起门卡。')]){const data=raw();data.nodes[0].completion_evidence=quote;assert.throws(()=>new A.Client().restoreAnalysis(original,data),e=>e.code==='BSE_EVIDENCE_INVALID');}});
test('一次列出所有证据错误，带节点/字段及拼接诊断',()=>{const data=raw();data.nodes[0].completion_evidence='没有凭证。……没有门卡。';data.nodes[1].completion_evidence='没有原件。';data.nodes[0].routes[0].condition_evidence=['我抽出带缺口的原件。','没有撤出。'];assert.throws(()=>new A.Client().restoreAnalysis(original,data),e=>e.evidence_issues.length===3 && e.message.includes('completion_evidence') && e.message.includes('condition_evidence') && e.message.includes('拼接'));});
test('定向补修只接受指定证据路径，模型额外修改条件/奖励无效且能恢复补修回复',async()=>{const data=raw();data.nodes[0].completion_evidence='没有凭证。……没有门卡。';let context;const f=mock(input=>input.operation==='repair_evidence'?{complete:true,evidence_fixes:input.fields.map(x=>({path:x.path,value:['信封里是一张临时访客凭证。','我拿起门卡。']})),nodes:[{id:'n1',result_ids:['fake'],routes:[{condition:true}]}]}:data);const result=await f.api.analyze(profile,original,'',{onResponse:r=>{if(r.kind==='repair')context=r;}});assert.equal(f.sent.length,2);assert.deepEqual(result.project.nodes[0].routes[0].condition,{collected:'card'});assert.deepEqual(result.project.nodes[0].effects,[{collect:'card'}]);assert.equal(context.repair_type,'evidence');const restored=f.api.restoreAnalysis(original,context.text,'faithful',context);assert.deepEqual(restored.project.nodes[0].effects,[{collect:'card'}]);});
test('补修未知路径、重复路径、无依据或complete:false不会放行，最多两次',async()=>{const data=raw();data.nodes[0].completion_evidence='不存在的证据';const f=mock(input=>input.operation==='repair_evidence'?{complete:true,evidence_fixes:[{path:['nodes',0,'result_ids'],value:[]}]}:data);await assert.rejects(f.api.analyze(profile,original),/未知或重复字段/);assert.equal(f.sent.length,3);assert.equal(f.sent.filter(x=>x.input.operation==='repair_evidence').length,2);});
test('作者流程使用不同提示词和独立模型，分析后复核实际转化的阶段事件',async()=>{const phases=[];const f=mock((input,body)=>{if(input.operation==='review_chunk')return {complete:true,issues:[]};if(input.operation==='review_script'){assert(input.converted.events.some(e=>e.completion_node_id));return {complete:true,issues:[]};}return raw();});const d=await f.api.analyze({...profile,author_review:true,review_model:'reviewer',review_prompt:'独立提取复核',review_script_prompt:'转化复核'},original,'',{onProgress:p=>phases.push(p)});assert.equal(f.sent.length,3);assert.equal(f.sent[0].body.model,'extract');assert.equal(f.sent[1].body.model,'reviewer');assert.equal(f.sent[1].body.messages[0].content,'独立提取复核');assert.equal(f.sent[2].body.messages[0].content,'转化复核');assert.equal(d.author_review.complete,true);assert.equal(d.review_blocked,false);assert.equal(d.request_count,3);assert(phases.some(p=>p.phase==='转化后复核'));});
test('分段复核发现错误，只重提取当前分段并再次独立复核，有上限且额外请求计数',async()=>{let reviews=0;const f=mock(input=>{if(input.operation==='review_chunk')return {complete:true,issues:++reviews===1?[{severity:'error',path:'nodes.0',message:'完成判断不可靠',quotes:['我拿起门卡。']}]:[]};if(input.operation==='review_script')return {complete:true,issues:[]};return raw();});const d=await f.api.analyze({...profile,author_review:true},original);assert.equal(f.sent.length,5);assert(f.sent[2].input.repair_issues.length);assert.equal(d.extra_request_count,2);assert.equal(d.review_blocked,false);});
test('转化复核有错误或被截断，草稿保留但不替换当前剧本',async()=>{for(const truncated of [false,true]){const f=mock(input=>input.operation==='review_chunk'?{complete:true,issues:[]}:input.operation==='review_script'?truncated?{finish:'length',data:{complete:true,issues:[]}}:{complete:true,issues:[{severity:'error',path:'nodes.0',message:'转化后的入口需核对',quotes:[]}]}:raw());const fx=fixture(),e=new Engine(fx.host,f.api);await e.init();await e.updateSettings({profile:{...profile,author_review:true}});const before=e.project.id;const d=await e.analyze(original);assert(d.review_blocked);assert(e.analysisDraft);assert.equal(e.project.id,before);if(!truncated)await assert.rejects(e.applyAnalysis(),/复核有待处理错误/);e.destroy();}});
test('复核回复不完整不当作通过；保留失败分析草稿，取消复核不应用晚到结果',async()=>{const f=mock(input=>input.operation==='review_chunk'?{complete:false,issues:[]}:raw());const fx=fixture(),e=new Engine(fx.host,f.api);await e.init();await e.updateSettings({profile:{...profile,author_review:true}});await assert.rejects(e.analyze(original),/不完整/);assert(e.analysisDraft?.is_partial);assert.equal(e.project.id,'hotel_demo');e.destroy();});
test('长篇转化复核按预算分组，所有节点和规则覆盖，单项不截断',async()=>{const text=original.repeat(200),p=C.normalizeProject({id:'large',title:'长篇',original_text:text,nodes:Array.from({length:15},(_,i)=>({id:'n'+i,title:'阶段'+i,guidance:'当前',detail:original.repeat(3),effects:[],routes:[]})),events:[],variables:[],collections:[]});const f=mock(input=>{assert.equal(input.grouped,true);return {complete:true,issues:[]};});const d=await f.api.reviewScript({...profile,max_input_chars:2200},text,p,C.convertAnalysisProject(p));assert(d.grouped);const checked=f.sent.flatMap(x=>x.input.units).filter(x=>x.kind==='nodes');assert.equal(new Set(checked.map(x=>x.id)).size,15);assert(f.sent.every(x=>x.body.messages.reduce((n,m)=>n+m.content.length,0)<=2200));});
