'use strict';
const http=require('node:http'),fs=require('node:fs'),assert=require('node:assert/strict'),{chromium}=require('playwright'),{fixture}=require('./helpers');
const content=JSON.parse(fs.readFileSync('branch_story_tavern_helper_import.json')).content;
const serialized=fixture.toString().replace('host: new Host(root)','host: null');
const source='## 开场\n玩家实际取得**房卡**，获得结果a。\n离开房间，结束调查。';
const requests=[],errors=[];
const server=http.createServer(async(req,res)=>{
 if(req.url==='/plugin.js'){res.setHeader('Content-Type','text/javascript; charset=utf-8');return res.end(content);}
 if(req.url==='/frame'){res.setHeader('Content-Type','text/html; charset=utf-8');return res.end('<!doctype html><script src="/plugin.js"></script>');}
 if(req.url==='/v1/chat/completions'){
  let body='';for await(const chunk of req)body+=chunk;const input=JSON.parse(JSON.parse(body).messages[1].content);requests.push(input);
  const value=input.operation==='repair_source'?{complete:true,node_sources:[{id:'n1',source_span:{from:'s1',to:'s1',start_quote:'玩家实际取得',end_quote:'获得结果a。'}},{id:'n2',source_span:{from:'s1',to:'s1',start_quote:'离开房间',end_quote:'结束调查。'}}]}:{title:'雨幕行动',collections:[{id:'a',title:'房卡',evidence:'玩家实际取得**房卡**，获得结果a。'}],nodes:[{id:'n1',title:'调查房间',detail:'你成功找到房卡。',guidance:'调查当前房间',completion_criteria:'实际取得房卡',completion_evidence:'玩家实际取得**房卡**，获得结果a。',result_ids:['a'],routes:[{target:'n2',label:'离开房间',condition:{collected:'a'},condition_evidence:'玩家实际取得**房卡**，获得结果a。'}]},{id:'n2',title:'撤离',detail:'离开房间，结束调查。',guidance:'离开房间',routes:[]}]};
  res.setHeader('Content-Type','application/json');return res.end(JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}]}));
 }
 res.setHeader('Content-Type','text/html; charset=utf-8');res.end(`<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"></head><body><div id="chat" style="height:500px"></div><div id="send_form"><textarea id="send_textarea"></textarea></div><script>const C={clone:v=>JSON.parse(JSON.stringify(v))};const fixture=${serialized};window.testHost=fixture();const saved=localStorage.getItem('bank');if(saved)Object.assign(testHost.storage,JSON.parse(saved));const original=testHost.root.updateVariablesWith;testHost.root.updateVariablesWith=function(...args){original.apply(this,args);localStorage.setItem('bank',JSON.stringify(testHost.storage));};for(const [name,value] of Object.entries(testHost.root))if(typeof value==='function')window[name]=value.bind(testHost.root);window.tavern_events={};</script><iframe src="/frame" style="display:none"></iframe></body></html>`);
});
const evaluate=(page,fn,arg)=>page.evaluate(({fn,arg})=>new Function('e','arg','return ('+fn+')(e,arg)')(document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine,arg),{fn:fn.toString(),arg});
const tab=(page,name)=>page.locator('[data-action="tab"][data-tab="'+name+'"]').click();
const bank=page=>page.locator('[data-action="library-open"]').click();
async function run(){
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const base='http://127.0.0.1:'+server.address().port,browser=await chromium.launch({headless:true,executablePath:process.env.BSE_CHROMIUM||'/usr/bin/chromium',args:['--no-sandbox']});
 try{for(const width of [1366,390,320]){
  const context=await browser.newContext({viewport:{width,height:950},isMobile:width<700,hasTouch:width<700}),page=await context.newPage();page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_startup__?.status==='ready');await page.locator('.launcher').click();assert((await page.locator('header').innerText()).includes('v'+require('../package.json').version));
  await evaluate(page,async e=>e.updateSettings({profile:{base_url:location.origin+'/v1',model:'mock',auto_partition:false}}));await bank(page);await page.locator('[name="project_title"]').fill('剧本甲');await page.locator('[data-action="project-new"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.title==='剧本甲');const a=await evaluate(page,e=>e.project.id);
  await tab(page,'analysis');await page.locator('[name="analysis_text"]').fill(source);const before=requests.length;await page.locator('[data-action="analysis-run"]').click();await page.waitForFunction(()=>!!document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.analysisDraft);assert.equal(requests.length-before,2);assert.equal(requests.at(-1).operation,'repair_source');assert.equal(await evaluate(page,e=>e.error),'');assert((await evaluate(page,e=>e.analysisDraft.project.nodes[0].detail)).includes('**房卡**'));
  await bank(page);await page.locator('[name="project_title"]').fill('剧本乙');await page.locator('[data-action="project-new"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.title==='剧本乙');const b=await evaluate(page,e=>e.project.id);assert.equal(await evaluate(page,e=>e.analysisDraft),null);assert.equal(await evaluate(page,e=>e.rawAnalysis),null);
  await tab(page,'analysis');await page.locator('[name="analysis_text"]').fill('乙自己的原文');await page.locator('[name="analysis_wish"]').fill('乙自己的要求');await page.locator('[name="project_switch"]').selectOption(a);await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.title==='剧本甲');assert.equal(await page.locator('[name="analysis_text"]').inputValue(),source);assert.equal(await evaluate(page,e=>e.analysisDraft.project.title),'雨幕行动');assert.equal(await evaluate(page,e=>e.rawAnalysis.replies.at(-1).kind),'repair');
  await page.locator('.section-nav button').filter({hasText:'恢复后台结果'}).click();const saved=await evaluate(page,e=>e.rawAnalysis.replies[0].id);await page.locator('[name="analysis_saved_id"]').selectOption(saved);await page.locator('[data-action="analysis-raw-load"]').click();const repairCount=requests.length;await page.locator('[data-action="analysis-repair"]').click();await page.waitForFunction(()=>{const e=document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine;return e.rawAnalysis.replies.length===3 && e.busy===0;});assert.equal(requests.length-repairCount,1);assert.equal(await evaluate(page,e=>e.rawAnalysis.error),'');
  page.once('dialog',d=>d.accept());await page.locator('[data-action="analysis-convert"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.title==='雨幕行动');const mission=await evaluate(page,e=>e.project.id);await evaluate(page,e=>e.complete());assert.deepEqual(await evaluate(page,e=>e.state.collected_ids),['a']);
  await page.locator('[name="project_switch"]').selectOption(b);await tab(page,'analysis');assert.equal(await page.locator('[name="analysis_text"]').inputValue(),'乙自己的原文');assert.equal(await page.locator('[name="analysis_wish"]').inputValue(),'乙自己的要求');assert.deepEqual(await evaluate(page,e=>e.state.collected_ids),[]);
  await page.locator('[name="project_switch"]').selectOption(mission);assert.deepEqual(await evaluate(page,e=>e.state.collected_ids),['a']);await bank(page);await page.locator('[data-action="project-copy"][data-id="'+mission+'"]').click();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.title.endsWith('（副本）'));assert.deepEqual(await evaluate(page,e=>e.state.collected_ids),[]);assert.equal(await evaluate(page,e=>e.settings.enabled),false);
  await bank(page);page.once('dialog',d=>d.dismiss());await page.locator('[data-action="project-remove"][data-id="'+b+'"]').click();assert(await evaluate(page,(e,id)=>e.projectList().some(p=>p.id===id),b));page.once('dialog',d=>d.accept());await page.locator('[data-action="project-remove"][data-id="'+b+'"]').click();await page.waitForFunction(id=>!document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.projectList().some(p=>p.id===id),b);
  await page.locator('[name="library_search"]').fill('雨幕');assert.equal(await page.locator('.library-item').count(),2);assert.equal(await page.locator('.library-item').filter({hasText:'剧本甲'}).count(),0);
  await page.locator('[name="project_switch"]').selectOption(mission);await page.reload();await page.waitForFunction(()=>document.querySelector('iframe').contentWindow.__branch_story_startup__?.status==='ready');assert.equal(await evaluate(page,e=>e.project.id),mission);assert.deepEqual(await evaluate(page,e=>e.state.collected_ids),['a']);await page.locator('.launcher').click();await bank(page);await page.locator('[name="library_search"]').fill('');
  assert((await page.locator('.library-item').count())>=4);assert((await page.locator('.project-switcher').evaluate(el=>el.scrollWidth-el.clientWidth))<=2);assert((await page.locator('main').evaluate(el=>el.scrollWidth-el.clientWidth))<=2);await page.screenshot({path:'/tmp/v144-library-'+width+'.png'});
  if(width===1366){await page.evaluate(()=>{window.previousPlugin=document.querySelector('iframe').contentWindow.__branch_story_plugin__;const frame=document.createElement('iframe');frame.src='/frame';frame.style.display='none';document.body.append(frame);});await page.waitForFunction(()=>document.querySelectorAll('iframe')[1].contentWindow.__branch_story_startup__?.status==='ready');await page.evaluate(async()=>{const current=document.querySelectorAll('iframe')[1].contentWindow.__branch_story_plugin__;await current.engine.updateSettings({enabled:true});});const injected=await page.evaluate(()=>testHost.root.injection.length);assert(injected>0);await page.evaluate(()=>previousPlugin.destroy());assert.equal(await page.evaluate(()=>testHost.root.injection.length),injected);assert.equal(await page.locator('#bse-panel-host').count(),1);}
  await context.close();console.log(width+'px：正文失败→来源补修→转换；多剧本工作区/编辑原文/独立进度/复制/搜索/确认删除/刷新恢复通过');
 }assert.deepEqual(errors,[]);}finally{await browser.close();await new Promise(r=>server.close(r));}
}
run().catch(e=>{console.error(e);process.exitCode=1});
