'use strict';
const http = require('node:http'), fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const {chromium} = require('playwright'), {fixture} = require('./helpers');
const root = path.resolve(__dirname, '..'), bundle = JSON.parse(fs.readFileSync(path.join(root, 'branch_story_tavern_helper_import.json'))).content;
const errors = [], requests = [];
const story = '玩家已拿到维修房卡。只是看到不算完成。';
const server = http.createServer(async (req, res) => {
  if (req.url === '/plugin.js') { res.setHeader('Content-Type', 'text/javascript'); return res.end(bundle); }
  if (req.url === '/frame') return res.end('<!doctype html><script src="/plugin.js"></script>');
  if (req.url === '/v1/chat/completions') {
    let body = ''; for await (const chunk of req) body += chunk; const request = JSON.parse(body), input = JSON.parse(request.messages[1].content); requests.push(input); let value;
    if (input.original) value = {title: '原始回复恢复', nodes: [{id: 'card', title: '房卡阶段', detail: input.original, guidance: '调查房卡', completion_criteria: '已拿到维修房卡', completion_exclusions: {wrong: true}, completion_evidence: story, routes: []}]};
    else if (input.candidates) value = {status: 'none'};
    else { const m = input.dialogue.at(-1); value = {status: m.text.includes('完成') ? 'completed' : 'in_progress', summary: m.text, facts: [{text: m.text, evidence: [{message_id: m.message_id, quote: m.text}]}], missing: m.text.includes('完成') ? [] : ['等待实际完成'], evidence: [{message_id: m.message_id, quote: m.text}]}; }
    res.setHeader('Content-Type', 'application/json'); return res.end(JSON.stringify({choices: [{finish_reason: 'stop', message: {content: JSON.stringify(value)}}]}));
  }
  res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.end(`<!doctype html><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#222}iframe{display:none}#send_form{position:fixed;bottom:8px;left:10px;right:10px}textarea{box-sizing:border-box;width:100%;height:55px}</style><form id="send_form"><textarea id="send_textarea"></textarea></form><script>const C={clone:x=>JSON.parse(JSON.stringify(x))};const fixture=${fixture.toString().replace('host: new Host(root)', 'host: null')};window.testHost=fixture();window.TavernHelper=testHost.root;window.sendRound=async(reply)=>{const h=testHost.root,field=document.querySelector('textarea'),text=field.value;field.value='';const id=h.messages.length;h.messages.push({message_id:id,role:'user',message:text});await h.eventEmit('message_sent',id);await h.eventEmit('generate_before_combine_prompts','normal');const injected=C.clone(h.injection),aid=h.messages.length;h.messages.push({message_id:aid,role:'assistant',message:reply});await h.eventEmit('message_received',aid);await h.eventEmit('generation_ended',aid);const e=document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine;await new Promise(r=>setTimeout(r,10));await e.stageJobs;return injected;};const f=document.createElement('iframe');f.src='/frame';document.body.appendChild(f);</script>`);
});
const evaluate = (page, fn, arg) => page.evaluate(({source, arg}) => new Function('e', 'panel', 'arg', 'return (' + source + ')(e,panel,arg)')(document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine, document.querySelector('iframe').contentWindow.__branch_story_plugin__.panel, arg), {source: fn.toString(), arg});
const tab = (page, name) => page.locator(`nav [data-tab="${name}"]`).click();
async function unlock(page) { await page.locator('[data-action="unlock-ask"]').click(); await page.locator('[data-action="unlock-confirm"]').click(); }
async function run() {
  await new Promise(r => server.listen(0, '127.0.0.1', r)); const base = 'http://127.0.0.1:' + server.address().port;
  const browser = await chromium.launch({headless: true, executablePath: process.env.BSE_CHROMIUM || '/usr/bin/chromium', args: ['--no-sandbox']});
  try {
    for (const width of [1366, 390, 320]) {
      const context = await browser.newContext({viewport: {width, height: width > 700 ? 900 : 844}, isMobile: width < 700, hasTouch: width < 700}), page = await context.newPage(); page.on('pageerror', error => errors.push(error.message)); page.on('dialog', d => d.accept()); await page.goto(base);
      await page.waitForFunction(() => document.querySelector('iframe')?.contentWindow.__branch_story_plugin__?.engine.chat);
      await evaluate(page, async e => e.updateSettings({profile: {base_url: location.origin + '/v1', model: 'mock'}})); await page.locator('.launcher').click();
      await tab(page, 'nodes'); await unlock(page); await page.locator('[data-action="node-tab"][data-tab="packages"]').click(); await page.locator('[data-action="package-demo"]').click(); assert.equal(await evaluate(page, e => e.project.packages.length), 4); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), ''); await unlock(page);
      await page.locator('details').filter({has: page.locator('summary', {hasText: '生成数值触发条件'})}).locator('summary').click(); await page.locator('[name="pack_value"]').fill('40'); await page.locator('[data-action="package-number-condition"]').click(); await page.locator('[data-action="package-save"]').click(); assert.equal(await evaluate(page, e => e.error), '', JSON.stringify(await evaluate(page, (e, panel) => ({error:e.error, condition:e.project.packages[0].condition, forms:panel.forms})))); await page.waitForFunction(() => document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.project.packages[0].condition.all?.[1]?.variable.value === 40);
      // Return the threshold to its original value, then use the actual enable button.
      await page.locator('[name="condition"]').fill('{"variable":{"id":"trust","op":"gte","value":30}}'); await page.locator('[data-action="package-save"]').click(); await tab(page, 'run'); await page.locator('[data-action="toggle-enabled"]').click();
      await tab(page, 'records'); await page.locator('[data-action="records-tab"][data-tab="graph"]').click(); assert.equal(await page.locator('.spoiler-content').getAttribute('aria-hidden'), 'true'); assert.equal(await evaluate(page, (e, panel) => panel.unlocked), true); assert.equal(await evaluate(page, (e, panel) => panel.runUnlocked), false);
      await page.locator('[data-action="unlock-ask"]').click(); await page.keyboard.press('Escape'); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), ''); assert(await page.locator('.overlay').isVisible()); await page.locator('[data-action="unlock-ask"]').click(); await page.locator('[data-action="unlock-cancel"]').click(); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), '');
      assert.equal(await evaluate(page, async (e, panel) => { try { await panel.action('graph-node', {dataset: {id: 'result:a4'}}); return false; } catch { return true; } }), true);
      await unlock(page); assert.equal(await page.locator('.spoiler-content').getAttribute('aria-hidden'), 'false'); assert(await page.locator('svg[aria-label="完成与解锁关系图"]').isVisible()); await page.locator('[name="graph_filter"]').selectOption('D'); assert(await page.locator('[data-id="result:b2"]').count()); await page.locator('[data-action="graph-zoom"][data-delta="0.25"]').click();
      assert(await evaluate(page, (e, panel) => { const main = panel.shadow.querySelector('main'), box = panel.shadow.querySelector('.graph-viewport'); return main.scrollWidth <= main.clientWidth + 1 && box.scrollWidth > box.clientWidth; }));
      fs.mkdirSync(path.join(root, 'artifacts'), {recursive:true}); await page.screenshot({path:path.join(root, 'artifacts', 'packages-graph-' + width + '.png')}); await page.locator('[data-action="spoiler-lock"]').click(); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), ''); await page.locator('[data-action="close"]').click();
      const before = await evaluate(page, e => e.state.current_node_id); await page.locator('[data-action="quick-enter"][data-id="B_2"]').click(); assert.equal(await evaluate(page, e => e.state.current_node_id), before); assert.equal(await page.locator('#send_textarea').inputValue(), '取出房卡'); const first = await page.evaluate(() => sendRound('完成取得维修房卡，房卡已收好。')); assert(first[0].content.includes('取得维修房卡')); assert.deepEqual(await evaluate(page, e => e.state.collected_ids), ['b2']);
      for (const [focus, result] of [['C', 'c1'], ['A', 'a4'], ['D', 'd1']]) { assert.equal(await evaluate(page, e => e.state.focus_package_id), focus); assert.equal(await evaluate(page, (e, p, code) => e.state.collected_ids.includes(code), result), false); await page.locator('#send_textarea').fill('继续处理这件事'); await page.evaluate(() => sendRound('完成当前阶段，已经核实。')); assert.equal(await evaluate(page, (e, p, code) => e.state.collected_ids.includes(code), result), true); }
      await page.locator('.launcher').click(); await tab(page, 'records'); await unlock(page); await page.locator('[name="graph_filter"]').selectOption(''); await page.locator('[data-id="result:b2"]').click(); await page.locator('[data-action="result-rollback"]').click(); assert.deepEqual(await evaluate(page, e => e.state.collected_ids), ['c1']); assert.equal(await evaluate(page, e => e.state.paused), true);
      await tab(page, 'analysis'); await page.locator('[name="analysis_text"]').fill(story); const count = requests.length; await page.locator('[data-action="analysis-run"]').click(); await page.waitForFunction(() => document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.error.includes('completion_exclusions')); assert.equal(requests.length, count + 1); assert(await page.locator('[name="analysis_response"]').isVisible()); const saved = JSON.parse(await page.locator('[name="analysis_response"]').inputValue()); saved.nodes[0].completion_exclusions = ['只是看到']; await page.locator('[name="analysis_response"]').fill(JSON.stringify(saved)); await page.locator('[data-action="analysis-restore"]').click(); assert.equal(await evaluate(page, e => e.analysisDraft.recovered), true); assert.equal(requests.length, count + 1);
      await tab(page, 'records'); assert.equal(await evaluate(page, (e, panel) => panel.recordUnlocked), true); await evaluate(page, e => { testHost.root.chat = 'chat2'; e.bindChat(); e.notify(); }); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), ''); assert.equal(await evaluate(page, (e, panel) => panel.unlocked || panel.runUnlocked || panel.recordUnlocked), false);
      console.log('事件包、箭头图、防剧透、连带回退与原始回复恢复：' + width + 'px 通过'); await context.close();
    }
    assert.deepEqual(errors, []); console.log('新增浏览器场景错误0；全部使用模拟API。');
  } finally { await browser.close(); await new Promise(r => server.close(r)); }
}
run().catch(error => { console.error(error); process.exitCode = 1; });
