'use strict';
const http = require('node:http'), fs = require('node:fs'), path = require('node:path'), assert = require('node:assert/strict');
const {chromium} = require('playwright'), {fixture} = require('./helpers');
const root = path.resolve(__dirname, '..'), bundle = JSON.parse(fs.readFileSync(path.join(root, 'branch_story_tavern_helper_import.json'))).content;
const requests = [], errors = [], fixtureText = fixture.toString().replace('host: new Host(root)', 'host: null');
const project = {id: 'player_ui', title: '输入栏与记录测试', start_node_id: 'N1', variables: [{id: 'rapport', title: '关系值', owner: '同行者', type: 'number', default: 69, min: 0, max: 100}], collections: [{id: 'b1', title: '房卡', description: '在储物间找到的房卡，上面写着301。'}, {id: 'secret', title: '隐藏真相', description: '未获得的最终答案'}], nodes: [{id: 'N1', title: '大厅', routes: [{target: 'N2', label: '调查储物间', action_text: '调查储物间'}]}, {id: 'N2', title: '调查储物间', effects: [{collect: 'b1'}], routes: []}, {id: 'N3', title: '后续调查', effects: [{collect: 'secret'}], routes: []}], events: [{id: 'E1', title: '赠礼被接受', description: '玩家赠礼且对方收下', completion_criteria: '实际交付并被接受', actor_id: 'player', effects: [{add: {variable: 'rapport', value: 4, max: 70}}], repeat_policy: 'once_per_accepted_turn', auto_settle: true}], packages: [{id: 'P1', title: '关系满足后的事件包', node_ids: ['N3'], condition: {variable: {id: 'rapport', op: 'gte', value: 70}}}]};
const server = http.createServer(async (req, res) => {
  if (req.url === '/plugin.js') { res.setHeader('Content-Type', 'text/javascript'); return res.end(bundle); }
  if (req.url === '/frame') return res.end('<!doctype html><html><body><script src="/plugin.js"></script></body></html>');
  if (req.url === '/v1/chat/completions') {
    let text = ''; for await (const chunk of req) text += chunk; const body = JSON.parse(text); requests.push(body); const input = JSON.parse(body.messages[1].content); let value;
    if (input.original) value = {title: '编辑提示词后的分析', nodes: [{id: 'unnecessarily_long_node_id', title: '找到房卡', detail: input.original, guidance: '调查当前房卡', routes: []}]};
    else if (input.candidates?.[0]?.description) { const source = input.dialogue.at(-1); value = {results: input.candidates.map(e => ({event_id: e.id, status: e.completion_criteria.includes('人工确认') ? 'uncertain' : source.text.includes('收下') ? 'completed' : 'not_occurred', actor_id: e.actor_id, recipient_id: e.recipient_id, evidence: [{message_id: source.message_id, quote: source.text}]}))}; }
    else if (input.candidates) { const candidate = input.candidates.find(r => input.dialogue[0].text.includes(r.action_text || r.label)); value = candidate ? {status: 'selected', target: candidate.target, evidence: [{message_id: input.dialogue[0].message_id, quote: input.dialogue[0].text}]} : {status: 'none'}; }
    else value = {status: 'in_progress', summary: '等待实际行动', facts: [], missing: [], evidence: []};
    res.setHeader('Content-Type', 'application/json'); return res.end(JSON.stringify({choices: [{finish_reason: 'stop', message: {content: JSON.stringify(value)}}], usage: {prompt_tokens: 50, completion_tokens: 20}}));
  }
  const fixed = req.url.includes('fixed'); res.setHeader('Content-Type', 'text/html; charset=utf-8');
  res.end(`<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><style>body{margin:0;background:#ddd;font:16px system-ui}#sheld{height:100dvh;display:flex;flex-direction:column}#chat{flex:1;min-height:0;overflow:auto;padding:12px;background:#eee}#send_form{flex:none;display:flex;align-items:center;gap:8px;margin:8px;padding:3px 7px}textarea{width:100%;height:44px;box-sizing:border-box}iframe{display:none}${fixed ? '#chat{position:absolute;left:0;right:0;top:0;bottom:70px}#send_form{position:fixed;bottom:0;left:0;right:0}' : ''}</style></head><body><div id="sheld"><div id="chat">${Array.from({length: 18}, (_, i) => '<p>正文段落' + i + '：夜色笼罩着大厅，玩家仍可自由行动。</p>').join('')}</div><form id="send_form"><textarea id="send_textarea"></textarea></form></div><script>const C={clone:v=>JSON.parse(JSON.stringify(v))};const fixture=${fixtureText};window.testHost=fixture();window.TavernHelper=testHost.root;testHost.storage.script.branch_story_settings={runtime_mode:'legacy',profile:{author_review:false,auto_partition:false},project_id:'player_ui',drafts:{player_ui:${JSON.stringify(project)}}};window.sendRound=async(input,response)=>{const h=testHost.root,id=h.messages.length;document.querySelector('textarea').value='';h.messages.push({message_id:id,role:'user',message:input});await h.eventEmit('message_sent',id);await h.eventEmit('generate_before_combine_prompts','normal');const aid=h.messages.length;h.messages.push({message_id:aid,role:'assistant',message:response});await h.eventEmit('message_received',aid);await h.eventEmit('generation_ended');};window.reloadPlugin=()=>{document.querySelector('iframe')?.remove();const f=document.createElement('iframe');f.src='/frame';document.body.appendChild(f);};reloadPlugin();</script></body></html>`);
});
const evaluate = (page, fn, arg) => page.evaluate(({source, arg}) => new Function('e', 'panel', 'arg', 'return (' + source + ')(e,panel,arg)')(document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine, document.querySelector('iframe').contentWindow.__branch_story_plugin__.panel, arg), {source: fn.toString(), arg});
const tab = (page, name) => page.locator(`nav [data-tab="${name}"]`).click();
async function ready(page) { await page.waitForFunction(() => document.querySelector('iframe')?.contentWindow?.__branch_story_startup__?.status === 'ready'); }
async function idle(page) { await evaluate(page, async e => { await e.stageJobs; await e.jobs; }); await page.waitForFunction(() => document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.busy === 0); }
async function layout(page) {
  await page.waitForFunction(() => { const q = document.querySelector('#bse-quick-host'), c = document.querySelector('#chat'), input = document.querySelector('textarea'); if (!q || q.hidden) return false; return c.getBoundingClientRect().bottom <= q.getBoundingClientRect().top + 1 && q.getBoundingClientRect().bottom <= input.getBoundingClientRect().top - 3; });
  const metrics = await page.evaluate(() => { const h = document.querySelector('#bse-quick-host'), q = h.shadowRoot.querySelector('.quick'), buttons = [...h.shadowRoot.querySelectorAll('button')].filter(x => x.getClientRects().length); return {overflow: q.scrollWidth - q.clientWidth, bodyOverflow: document.documentElement.scrollWidth - innerWidth, touch: buttons.every(x => x.getBoundingClientRect().width >= 44 && x.getBoundingClientRect().height >= 44)}; });
  assert.equal(metrics.overflow, 0); assert(metrics.bodyOverflow <= 1); assert(metrics.touch);
}
async function run() {
  await new Promise(r => server.listen(0, '127.0.0.1', r)); const base = 'http://127.0.0.1:' + server.address().port, browser = await chromium.launch({headless: true, executablePath: process.env.BSE_CHROMIUM || '/usr/bin/chromium', args: ['--no-sandbox']});
  try {
    for (const width of [1366, 390, 320]) {
      const context = await browser.newContext({viewport: {width, height: width > 700 ? 900 : 844}, isMobile: width < 700, hasTouch: width < 700}), page = await context.newPage(); let accept = true;
      page.on('pageerror', e => errors.push(e.message)); page.on('dialog', d => accept ? d.accept() : d.dismiss()); await page.goto(base + (width === 320 ? '/fixed' : '/')); await ready(page);
      await page.locator('.launcher').click(); await tab(page, 'api'); await page.locator('[name="base_url"]').fill(base); await page.locator('[name="model"]').fill('mock'); await page.locator('[data-action="api-save"]').first().click();
      await tab(page, 'run'); await page.locator('[data-action="toggle-enabled"]').click(); await page.locator('[data-action="close"]').click(); await page.locator('#bse-quick-host').waitFor({state: 'visible'}); await layout(page);
      assert((await page.locator('.quick-title').innerText()).includes('大厅')); assert.equal(await page.locator('[data-action="quick-complete"]').count(), 0); assert.equal(await page.locator('[data-action="quick-enter"]').count(), 1);
      await page.locator('[data-action="quick-enter"]').click(); const draft = await page.locator('textarea').inputValue(); assert.equal(draft, '调查储物间'); assert.equal(await evaluate(page, e => e.state.current_node_id), 'N1');
      const expanded = (await page.locator('#bse-quick-host').boundingBox()).height; await page.locator('[data-action="quick-collapse"]').click(); assert(await page.locator('[data-action="quick-enter"]').isHidden()); assert((await page.locator('#bse-quick-host').boundingBox()).height < expanded); assert.equal(await page.locator('textarea').inputValue(), draft); assert.equal(await evaluate(page, e => !!e.pendingChoice), true); await layout(page);
      await page.locator('[data-action="quick-collapse"]').click(); await page.evaluate(() => sendRound('调查储物间', '你来到储物间，发现桌上的房卡。')); await idle(page); assert.equal(await evaluate(page, e => e.state.current_node_id), 'N2'); assert.equal(await page.locator('[data-action="quick-enter"]').count(), 0); assert(await page.locator('#bse-quick-host').isVisible());
      await page.locator('[data-action="quick-bag"]').click(); assert((await page.locator('.quick-menu').innerText()).includes('尚未获得')); assert(!(await page.locator('.quick-menu').innerText()).includes('隐藏真相'));
      await page.evaluate(() => sendRound('我拾起房卡。', '你将写着301的房卡收入衣袋。')); await idle(page); await page.locator('[data-action="quick-gear"]').click(); await page.locator('[data-action="quick-complete"]').click(); assert.deepEqual(await evaluate(page, e => e.state.collected_ids), ['b1']); assert(await page.locator('[data-action="quick-complete"]').isDisabled());
      await page.locator('[data-action="quick-bag"]').click(); await page.locator('.quick-menu .acquired summary').click(); assert((await page.locator('.quick-menu').innerText()).includes('在储物间找到的房卡，上面写着301。')); assert((await page.locator('.quick-menu').innerText()).includes('来源：调查储物间')); assert(!(await page.locator('.quick-menu').innerText()).includes('最终答案')); await layout(page); await page.screenshot({path: path.join(root, 'artifacts', 'player-bag-' + width + '.png')});
      await page.locator('[data-action="quick-gear"]').click(); await page.locator('[data-action="quick-pause"]').click(); assert.equal(await evaluate(page, e => e.state.paused), true); assert((await page.locator('[data-action="quick-pause"]').innerText()).includes('继续')); await page.locator('[data-action="quick-pause"]').click(); assert.equal(await evaluate(page, e => e.state.paused), false);
      await page.evaluate(() => sendRound('我把礼物交给你。', '对方收下了你递来的礼物。')); await page.waitForFunction(() => document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.state.variables.rapport === 70); await idle(page); assert.equal(await evaluate(page, e => e.state.event_counts.E1), 1); assert.equal(await evaluate(page, e => e.state.focus_package_id), 'P1');
      await page.locator('[data-action="quick-check"]').click(); await idle(page); assert.equal(await evaluate(page, e => e.state.variables.rapport), 70); assert.equal(await evaluate(page, e => e.state.event_counts.E1), 1);
      await page.locator('[data-action="quick-panel"]').click(); await tab(page, 'data'); assert((await page.locator('.values-card').innerText()).includes('69 → 70'));
      await page.locator('[name="value_title"]').fill('警戒值'); await page.locator('[name="value_owner"]').fill('全局'); await page.locator('[name="value_default"]').fill('2'); await page.locator('[name="value_max"]').fill('10'); await page.locator('[data-action="variable-new"]').click(); assert.equal(await evaluate(page, e => e.project.variables.find(x => x.title === '警戒值').id), 'V1'); assert.equal(await evaluate(page, e => e.state.variables.V1), 2); assert.equal(await evaluate(page, e => e.state.variables.rapport), 70);
      await page.locator('[data-action="variable-select"][data-id="rapport"]').click(); await page.locator('[name="value_default"]').fill('8'); await page.locator('[data-action="variable-save"]').click(); assert.equal(await evaluate(page, e => e.state.variables.rapport), 70);
      await tab(page, 'events'); await page.locator('[data-action="event-new"]').click(); await page.locator('[name="title"]').fill('需要确认的行为'); await page.locator('[name="completion_criteria"]').fill('需要人工确认实际完成'); await page.locator('[name="effect_variable"]').selectOption('V1'); await page.locator('[name="effect_delta"]').fill('2'); await page.locator('[data-action="append-effect"]').click(); await page.locator('[data-action="event-save"]').click(); assert.equal(await evaluate(page, e => e.project.events.at(-1).id), 'E2');
      await page.locator('[data-action="close"]').click(); await page.evaluate(() => sendRound('我尝试执行这项行动。', '行动的结果还不明确。')); await page.waitForFunction(() => document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.state.pending_checks.some(c => c.results.some(r => r.event_id === 'E2' && r.status === 'uncertain'))); await idle(page);
      if (await page.locator('[data-action="quick-gear"]').getAttribute('aria-expanded') === 'false') await page.locator('[data-action="quick-gear"]').click(); assert(await page.locator('.quick-dot').isVisible()); assert.equal(await evaluate(page, e => e.state.variables.V1), 2); await page.locator('[data-action="quick-accept"]').click(); assert.equal(await evaluate(page, e => e.state.variables.V1), 4); assert.equal(await page.locator('.quick-dot').count(), 0); await page.locator('[data-action="quick-panel"]').click(); await tab(page, 'data');
      await page.locator('[data-action="definition-select"][data-id="b1"]').click(); await page.locator('[name="result_description"]').fill('在储物间取得的301房卡。'); await page.locator('[data-action="definition-save"]').click();
      await tab(page, 'records'); await page.locator('[data-action="records-tab"][data-tab="graph"]').click(); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), '');
      await page.locator('[data-action="unlock-ask"]').click(); await page.locator('[data-action="unlock-cancel"]').click(); assert.equal(await page.locator('.spoiler-content').getAttribute('inert'), ''); await page.locator('[data-action="unlock-ask"]').click(); await page.locator('[data-action="unlock-confirm"]').click();
      assert((await page.locator('.completion-records').innerText()).includes('房卡（b1）')); await page.locator('.completion-records .acquired').filter({hasText: '房卡（b1）'}).locator('summary').click(); assert((await page.locator('.completion-records').innerText()).includes('在储物间取得的301房卡。'));
      await page.locator('[data-action="graph-node"][data-id="result:b1"]').click(); await page.locator('[data-action="result-delete-ask"]').click(); assert(await page.locator('[data-action="result-delete-confirm"]').isDisabled()); await page.locator('[data-action="result-delete-cancel"]').click();
      await evaluate(page, async e => e.editProject(p => { p.collections.push({id: 'FLOWER_ACCEPTED', title: '旧送花结果'}); p.nodes.push({id: 'N4', title: '关联支线', entry_condition: {collected: 'FLOWER_ACCEPTED'}, routes: []}); p.packages.push({id: 'P2', title: '关联事件包', node_ids: ['N4'], condition: {collected: 'FLOWER_ACCEPTED'}, enabled: false}); })); assert.equal(await evaluate(page, e => e.settings.enabled), false);
      await page.locator('[data-action="graph-node"][data-id="result:FLOWER_ACCEPTED"]').click(); await page.locator('[data-action="result-delete-ask"]').click(); assert((await page.locator('.result-delete-editor').innerText()).includes('关联事件包')); assert((await page.locator('.result-delete-editor').innerText()).includes('关联支线'));
      accept = false; await page.locator('[data-action="result-delete-confirm"]').click(); assert.equal(await evaluate(page, e => e.project.collections.some(x => x.id === 'FLOWER_ACCEPTED')), true);
      accept = true; await page.locator('[data-action="result-delete-confirm"]').click(); assert.equal(await evaluate(page, e => e.project.collections.some(x => x.id === 'FLOWER_ACCEPTED')), false); assert.equal(await page.locator('[data-action="graph-node"][data-id="result:FLOWER_ACCEPTED"]').count(), 0); assert.equal(await evaluate(page, e => e.project.packages.find(x => x.id === 'P2').condition), false); assert.equal(await evaluate(page, e => e.diagnostics().filter(x => x.severity === 'error').length), 0); assert.equal(await evaluate(page, e => e.error), '');
      await tab(page, 'run'); await page.locator('[data-action="toggle-enabled"]').click(); assert.equal(await evaluate(page, e => e.settings.enabled), true);
      await tab(page, 'analysis'); await page.locator('.analysis-prompts > summary').click(); await page.locator('[name="analysis_prompt"]').fill('自定义分析系统提示词，请返回兼容JSON。'); await page.locator('[name="analysis_merge_prompt"]').fill('自定义合并系统提示词。'); await page.locator('[data-action="analysis-prompts-save"]').click();
      await tab(page, 'api'); assert.equal(await page.locator('[name="analysis_prompt"]').inputValue(), '自定义分析系统提示词，请返回兼容JSON。'); await tab(page, 'analysis'); await page.locator('[name="analysis_text"]').fill('在储物间找到301房卡。'); await page.locator('[name="analysis_wish"]').fill('只整理已明确的内容'); await page.locator('[data-action="analysis-preview"]').click(); assert((await page.locator('.prompt-preview').innerText()).includes('自定义分析系统提示词'));
      const before = requests.length; await page.locator('[data-action="analysis-run"]').click(); await page.waitForFunction(() => !!document.querySelector('iframe').contentWindow.__branch_story_plugin__.engine.analysisDraft); assert.equal(requests.length, before + 1); assert.equal(requests.at(-1).messages[0].content, '自定义分析系统提示词，请返回兼容JSON。'); assert.equal(await evaluate(page, e => e.analysisDraft.project.nodes[0].id), 'N1'); assert.deepEqual(await evaluate(page, e => JSON.parse(e.rawAnalysis.requests[0].text)), requests.at(-1).messages);
      await page.locator('[data-action="close"]').click(); await page.locator('[data-action="quick-collapse"]').click(); await page.evaluate(() => reloadPlugin()); await ready(page); assert.equal(await evaluate(page, e => e.settings.quick_collapsed), true); assert.equal(await page.locator('#bse-quick-host').count(), 1); await page.locator('[data-action="quick-bag"]').click(); await page.locator('.quick-menu summary').click(); assert((await page.locator('.quick-menu').innerText()).includes('在储物间取得的301房卡。')); await layout(page);
      await evaluate(page, (e, panel) => { panel.destroy(); }); assert.equal(await page.locator('#bse-quick-host').count(), 0); assert.equal(await page.locator('#send_form').evaluate(el => el.style.paddingTop), ''); assert.equal(await page.locator('#chat').evaluate(el => el.style.maxHeight), '');
      console.log(width + 'px：当前阶段/折叠/⚙️/🎒/正文空间/数值奖励/结果删除/提示词保存与实发/刷新/卸载通过'); await context.close();
    }
    assert.deepEqual(errors, []); console.log('玩家小面板新增浏览器错误0；模拟API。');
  } finally { await browser.close(); await new Promise(r => server.close(r)); }
}
run().catch(e => { console.error(e); process.exitCode = 1; });
