'use strict';
const test = require('node:test'), assert = require('node:assert/strict');
const C = require('../src/core'), API = require('../src/api'), {Engine, defaults} = require('../src/engine'), {fixture} = require('./helpers');
const original = '信任初始为30。拿到维修房卡记为b2。已有b2才开始核验，实际核验成功记为a4。';
const raw = () => ({title: '房卡核验', start_node_id: 'card', variables: [{id: 'trust', title: '信任', type: 'number', default: 30, evidence: '信任初始为30。'}], collections: [{id: 'b2', title: '维修房卡', evidence: '拿到维修房卡记为b2。'}, {id: 'a4', title: '核验完成', evidence: '实际核验成功记为a4。', requires: {collected: 'b2'}, requires_evidence: '已有b2才开始核验'}], nodes: [{id: 'card', title: '取得房卡', guidance: '玩家尝试取得房卡', detail: original, completion_criteria: '拿到维修房卡', completion_exclusions: [], completion_evidence: '拿到维修房卡记为b2。', result_ids: ['b2'], routes: []}, {id: 'verify', title: '核验', guidance: '玩家尝试核验', detail: '已有b2才开始核验，实际核验成功记为a4。', completion_criteria: '实际核验成功', completion_exclusions: [], completion_evidence: '实际核验成功记为a4。', result_ids: ['a4'], entry_condition: {collected: 'b2'}, entry_condition_evidence: '已有b2才开始核验', routes: []}], packages: [{id: 'card_case', title: '取得房卡', node_ids: ['card'], condition: {variable: {id: 'trust', op: 'gte', value: 30}}, condition_evidence: '信任初始为30。'}, {id: 'verify_case', title: '核验事件', node_ids: ['verify'], condition: {collected: 'b2'}, condition_evidence: '已有b2才开始核验'}]});
const profile = {...defaults().profile, auto_partition: false, base_url: 'https://mock.test/v1', model: 'mock'};
test('完成字段只规范文本数组/换行文本，不猜测对象语义，错误包含节点与字段', () => {
  const api = new API.Client(); const data = raw(); data.nodes[0].completion_criteria = ['已拿到', '已收好']; data.nodes[0].completion_exclusions = '只是看到\n打算拿';
  const draft = api.restoreAnalysis(original, JSON.stringify(data)); assert.equal(draft.project.nodes[0].completion_criteria, '已拿到\n已收好'); assert.deepEqual(draft.project.nodes[0].completion_exclusions, ['只是看到', '打算拿']); assert(draft.warnings.some(x => x.includes('格式')));
  data.nodes[0].completion_exclusions = {wrong: true}; assert.throws(() => api.restoreAnalysis(original, data), /取得房卡.*completion_exclusions/); data.nodes[0].completion_exclusions = []; data.nodes[0].completion_criteria = 42; assert.throws(() => api.restoreAnalysis(original, data), /取得房卡.*completion_criteria/);
  assert.throws(() => api.restoreAnalysis(original, ''), /请先粘贴/); assert(profile.analysis_prompt.includes('completion_criteria为字符串'));
});
test('验证失败前保存完整回复，刷新可修复，恢复零额外请求、原项目不替换、导出无密钥', async () => {
  const f = fixture(); let calls = 0; const data = raw(); data.nodes[0].completion_exclusions = {wrong: true}; const api = new API.Client(async () => { calls++; return {ok: true, json: async () => ({choices: [{finish_reason: 'stop', message: {content: JSON.stringify(data)}}]})}; }); const e = new Engine(f.host, api); await e.init(); await e.updateSettings({profile: {...profile, key: 'PRIVATE_RECOVERY_KEY'}});
  await assert.rejects(e.analyze(original), /completion_exclusions/); assert.equal(calls, 1); assert.equal(e.project.id, 'hotel_demo'); assert.equal(e.rawAnalysis.replies.length, 1); assert(JSON.parse(e.rawAnalysis.replies[0].text).nodes[0].completion_exclusions.wrong); assert(!JSON.stringify(e.rawAnalysis).includes('PRIVATE_RECOVERY_KEY'));
  const fresh = new Engine(f.host, api); await fresh.init(); const saved = fresh.rawAnalysis.replies[0]; const fixed = JSON.parse(saved.text); fixed.nodes[0].completion_exclusions = []; const result = fresh.restoreAnalysis(original, JSON.stringify(fixed), 'faithful', saved.id); assert.equal(result.request_count, 0); assert.equal(result.recovered, true); assert.equal(calls, 1); assert.equal(fresh.project.id, 'hotel_demo'); assert.equal(fresh.analysisDraft.project.packages.length, 2);
  assert.throws(() => fresh.restoreAnalysis(original + '新增', JSON.stringify(fixed), 'faithful', saved.id), /原文和处理方式/); assert.throws(() => fresh.restoreAnalysis(original, JSON.stringify(fixed), 'expand', saved.id), /原文和处理方式/);
});
test('length截断在格式校验前保留且禁止作为完整草稿恢复，提示分析输出预算，无重试', async () => {
  const f = fixture(); let calls = 0; const api = new API.Client(async () => { calls++; return {ok: true, json: async () => ({choices: [{finish_reason: 'length', message: {content: '{"nodes":['}}]})}; }); const e = new Engine(f.host, api); await e.init(); await e.updateSettings({profile});
  await assert.rejects(e.analyze(original), error => error.message.includes('截断') && error.message.includes('分析最大输出Token')); const reply = e.rawAnalysis.replies[0]; assert.equal(reply.text, '{"nodes":['); assert.equal(reply.finish_reason, 'length'); assert.throws(() => e.restoreAnalysis(original, JSON.stringify(raw()), 'faithful', reply.id), /截断/); assert.equal(calls, 1);
});
test('整合失败保留分块骨架，修改整合报告后恢复全篇；单块恢复明确标记部分草稿', async () => {
  const f = fixture(), text = ('甲段调查。\n乙段核验。\n').repeat(60); let calls = 0, mergeInput;
  const api = new API.Client(async (url, options) => { const req = JSON.parse(options.body), input = JSON.parse(req.messages[1].content); calls++; let value;
    if (input.original) value = {title: '分块', nodes: [{id: 'x', title: '阶段', guidance: '调查本阶段', detail: input.original, routes: []}]};
    else { mergeInput = input; value = {title: '合并', nodes: input.nodes.slice(1), analysis: {synopsis: '调查与核验'}}; }
    return {ok: true, json: async () => ({choices: [{finish_reason: 'stop', message: {content: JSON.stringify(value)}}]})}; });
  const e = new Engine(f.host, api); await e.init(); await e.updateSettings({profile: {...profile, analysis_prompt: '分析', analysis_merge_prompt: '合并', max_input_chars: 800}}); await assert.rejects(e.analyze(text), /遗漏或重复/); const before = calls, merge = e.rawAnalysis.replies.at(-1); assert.equal(merge.kind, 'merge'); assert(merge.nodes.length > 1);
  const fixed = {title: '恢复合并', nodes: mergeInput.nodes.map(n => ({id: n.id, routes: n.routes})), analysis: {synopsis: '已恢复'}}; const restored = e.restoreAnalysis(text, JSON.stringify(fixed), 'faithful', merge.id); assert.equal(restored.project.nodes.length, merge.nodes.length); assert.equal(restored.project.original_text, text); assert.equal(restored.is_partial, undefined); assert.equal(calls, before);
  const chunk = e.rawAnalysis.replies[0]; const partial = e.restoreAnalysis(chunk.original_from_run ? e.rawAnalysis.original : chunk.original, chunk.text, 'faithful', chunk.id); assert.equal(partial.is_partial, true); assert(partial.warnings.some(x => x.includes('不是全篇'))); assert.equal(calls, before);
});
test('本轮支线独立结算且不会使下一主包消费同一回复；配置变化拒绝晚到完成', async () => {
  const F = require('../src/flow'), {mockClient, deferred} = require('./helpers'); const f = fixture(), p = F.demoProject(), client = mockClient(); p.nodes.push({id: 'S1', title: '旁支', guidance: '调查门牌', completion_criteria: '门牌已记录', effects: [{collect: 's1'}], routes: []}); p.collections.push({id: 's1', title: '门牌记录'}); p.packages.push({id: 'S', title: '旁支', node_ids: ['S1'], role: 'side', priority: 1}); const seen = [];
  client.evaluateStage = async (profile, dialogue, node) => { seen.push(node.id); return {status: 'completed', summary: '', facts: [], missing: [], evidence: []}; }; const e = new Engine(f.host, client); await e.init(); await e.setProject(p); await e.updateSettings({enabled: true, profile}); e.enter('B_2'); e.state.turn_context = {user_id: 0, node_id: 'B_2', injection_nodes: F.activeNodes(e.project, e.state)}; await e.checkStage(); assert.deepEqual(seen, ['B_2', 'S1']); assert.deepEqual(e.state.collected_ids, ['b2', 's1']); assert.equal(e.state.focus_package_id, 'C'); assert.equal(e.state.package_progress.S.status, 'done');
  const ready = deferred(), gate = deferred(); client.evaluateStage = async () => { ready.resolve(); return gate.promise; }; e.state.turn_context = {user_id: 0, node_id: 'C_1', injection_nodes: F.activeNodes(e.project, e.state)}; const job = e.checkStage(); await ready.promise; await e.updateSettings({detail: true}); gate.resolve({status: 'completed', summary: '', facts: [], missing: [], evidence: []}); await job; assert(!e.state.collected_ids.includes('c1'));
});
test('后文分块继承前文数值定义，整合保留事件包条件及原文证据，不会合并成无条件', async () => {
  const text = '信任初始为30。\n' + '逐步调查房间。\n'.repeat(350); let chunks = 0;
  const api = new API.Client(async (url, options) => { const input = JSON.parse(JSON.parse(options.body).messages[1].content); let data;
    if (input.original) { chunks++; data = {title: '数值分块', variables: chunks === 1 ? [{id: 'trust', title: '信任', type: 'number', default: 30, evidence: '信任初始为30。'}] : [], nodes: [{id: 'x', title: '调查' + chunks, detail: input.original, guidance: '调查当前房间', routes: []}], packages: [{id: 'pack' + chunks, title: '调查包' + chunks, node_ids: ['x'], condition: {variable: {id: 'trust', op: 'gte', value: 30}}, condition_evidence: '信任初始为30。'}]}; }
    else data = {title: '合并事件包', nodes: input.nodes.map(n => ({id: n.id, routes: n.routes}))};
    return {ok: true, json: async () => ({choices: [{finish_reason: 'stop', message: {content: JSON.stringify(data)}}]})}; });
  const draft = await api.analyze({...profile, analysis_prompt: '分析', analysis_merge_prompt: '合并', max_input_chars: 3200}, text); assert(chunks > 1); assert.equal(draft.project.variables.length, 1); assert.equal(draft.project.packages.length, chunks); assert(draft.project.packages.every(b => b.condition.variable.id === 'trust' && b.condition_evidence === '信任初始为30。'));
});
