from pathlib import Path
import base64
out=Path(__file__).resolve().parent
engine=(out/'engine.cjs').read_text()
img=base64.b64encode((out/'map.jpg').read_bytes()).decode()
html='''<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>幽寂谷 · 地图事件链试行</title><style>
*{box-sizing:border-box}body{margin:0;background:#eee9de;color:#253d38;font:16px/1.65 system-ui,"Microsoft Yahei",sans-serif}header{background:#203d36;color:#f5ecdc;padding:24px 5vw}header h1{margin:0;font:30px Georgia,serif;letter-spacing:5px}header small{color:#c6cdbb}.wrap{max-width:1250px;margin:auto;padding:24px;display:grid;grid-template-columns:1.4fr 1fr;gap:24px}.map{position:relative;border:1px solid #a69472;border-radius:12px;overflow:hidden}.map img{width:100%;display:block}.pin{position:absolute;left:47%;top:53%;box-shadow:0 0 0 5px #f6edd699;background:#244e42;color:white}.card{background:#faf8f1;border:1px solid #d4ccbb;border-radius:12px;padding:22px;margin-bottom:18px}h2{font-size:21px;margin:0 0 12px}button,select,input,textarea{font:inherit}button{padding:10px 15px;border:1px solid #9c9d81;border-radius:7px;background:#e9e5d6;color:#203d36;cursor:pointer;min-height:44px}button:hover{background:#d9e5d8}button:disabled{opacity:.5;cursor:not-allowed}.actions{display:grid;gap:9px}.actions button{text-align:left;background:#244e42;color:#fff}.actions button:disabled{background:#888c7c}.row{display:flex;gap:8px;flex-wrap:wrap;align-items:center}textarea{width:100%;min-height:90px;border:1px solid #b9bdab;border-radius:7px;padding:12px;background:#fffef9}.muted{font-size:13px;color:#697668}.tag{display:inline-block;padding:4px 10px;background:#e1e8dc;border-radius:20px;margin:3px}#notice{padding:14px 16px;margin:12px 0;border:2px solid #b77e2d;border-radius:8px;background:#fff0cf;color:#57360b;font-weight:650;white-space:pre-line}#status{padding:12px;border-left:4px solid #346b53;background:#e5eddf;white-space:pre-line;margin:12px 0}.actions button.exit{background:#823b2e}.actions button.forward{background:#a17c35}.receipt{white-space:pre-line}ol{padding-left:23px;max-height:260px;overflow:auto}.receipt{border-left:4px solid #a88542;padding-left:14px}summary{cursor:pointer}label{display:block;margin:8px 0}input{max-width:90px;padding:6px;border:1px solid #b8bba8}footer{padding:15px 24px;text-align:center;color:#6d7468;font-size:13px}@media(max-width:780px){.wrap{grid-template-columns:1fr;padding:14px;gap:10px}header{padding:20px}header h1{font-size:25px}.card{padding:16px}.pin{padding:5px 8px;font-size:13px}}
</style><header><small>仙姝堕 · 南疆探索 / 可点击模板 v0.2</small><h1>幽寂谷 · 机缘之间</h1><div id="date"></div></header><main class="wrap"><section><div class="map"><img src="data:image/jpeg;base64,IMAGE" alt="基米提供的南疆全域地图"><button class="pin" id="enter">幽寂谷 · 进入</button></div><p class="muted">地图标记位置为试排，待确认正式坐标。开放窗口：1578年3月1日—4月30日。</p><div class="card"><h2>行囊与记录</h2><div id="bag"></div><div id="known" class="muted"></div></div><div class="card"><details><summary>试行设置</summary><p class="muted">退出耗时、叙事预算和未命名奖励均为测试配置，未写入生产角色卡。每月30日沿用现有历法。</p><label>身份 <select id="identity"><option>自设</option><option>赵无忧</option><option>焚欲殿主</option><option>欢喜殿主</option><option>浊龙殿主</option><option>魂欢殿主</option></select></label><div class="row"><label>月 <input id="month" type="number" min="1" max="12" value="3"></label><label>日 <input id="day" type="number" min="1" max="30" value="1"></label><button id="reset">以此日期重开</button></div><p class="muted">测试日期固定为1578年；重开会清空本次试玩存档。</p><div class="row"><button id="undo">撤回最近一步</button><button id="export">导出试玩存档</button></div></details></div></section><section><div class="card"><small id="phase" class="muted"></small><h2 id="title"></h2><p id="intro"></p><div id="status"></div><div id="notice" role="status" aria-live="polite"></div><div id="actions" class="actions"></div><div id="receipt"></div></div><div class="card" id="chat"><h2>自由活动</h2><p class="muted">提交一次模拟已成功生成的故事回复，消耗1轮选项期限；不会推进世界日期，也不会自动发奖。</p><textarea id="text" placeholder="例如：我留在谷口观察四周……"></textarea><button id="talk">记录一轮自由活动</button></div><div class="card"><h2>本次足迹</h2><ol id="log"></ol></div></section></main><footer>独立浏览器试玩 · 不连接模型/API · 不改酒馆存档 · 刷新可恢复进度</footer><script>ENGINE</script><script>
const E=Youjigu,$=id=>document.getElementById(id),key='xsd-youjigu-v01';let state=E.initial(),history=[],notice='';
try{const saved=JSON.parse(localStorage.getItem(key));if(saved&&saved.state?.version===1&&Number.isInteger(saved.state.stamp)&&Array.isArray(saved.state.used)){state=saved.state;history=saved.history||[];}}catch(e){notice='本地存档不可用，已启动新试玩。';}
const names={map:'南疆地图',first:'第一轮 · 选择探索方向',cave:'洞府 · 两处机缘',stream:'山涧 · 自由探查',second:'第二轮 · 深入探索',valley:'山谷 · 出口在前',secret:'密室 · 二选一',done:'结算完成'};
const descriptions={map:'确认身份后，点击地图标记进入幽寂谷。',first:'洞府保留3轮，山涧保留5轮。离开子区域会回到这里；其它未访问且未过期的入口仍可选。确认不再探索后，再进入第二轮。',cave:'香炉与暗格只能选择一项。选定后，另一项立即消失。',stream:'可查看溪水、树丛，也可自由活动后离开。',second:'选择继续探索的区域。',valley:'可收集草药，或从出口结束本次事件。',secret:'你已凭地图进入密室。两侧暗格只能开启一个；正式剧情待填。',done:'本次事件已结束，以下为脚本核算的回执。重新试玩请打开“试行设置”。'};
function persist(){try{localStorage.setItem(key,JSON.stringify({state,history}));}catch(e){notice='浏览器未允许保存：本次进度仅保留到页面关闭。';}}
function commit(result,message='操作已完成'){ if(!result.ok){notice=result.error;render();return;}history.push(structuredClone(state));state=result.state;notice=message;persist();render();}
function render(){ $('date').textContent=E.date(state.stamp)+' · '+state.identity+' · 对话 '+state.turn+' 轮';$('phase').textContent=state.step==='map'?'南疆 · 地图选择':'幽寂谷 · '+(state.step==='done'?'事件已结束':'事件进行中');$('title').textContent=names[state.step];$('intro').textContent=descriptions[state.step]+(!['map','done'].includes(state.step)?' '+E.config.budget:'');$('notice').textContent=notice||'请选择当前区域的行动。';$('status').textContent=['map','done'].includes(state.step)?(state.step==='done'?'本次事件已结束，时间已结算。':'点击幽寂谷标记开始探索。'): '当前：'+names[state.step]+' · 世界时间保持不变。'+(state.step==='first'?'\\n'+['k4m8','s9a3'].map(id=>{const a=E.defs[id];return a.label+'：'+(state.used.includes(id)?'已探索':state.turn-state.created>=a.ttl?'已过期':'剩余'+(a.ttl-state.turn+state.created)+'轮');}).join('；'):'');$('actions').replaceChildren();for(const a of E.options(state)){if(a.from==='map')continue;const b=document.createElement('button');b.textContent=a.label+(a.remaining!==null?' · 剩余'+a.remaining+'轮':'')+(a.blocked?'（'+a.blocked+'）':'');b.disabled=!!a.blocked;if(a.finish||a.early)b.className='exit';b.onclick=()=>choose(a.id);$('actions').append(b);}if(state.step==='first'){const b=document.createElement('button');b.className='forward';b.textContent='结束第一轮 · 进入第二轮';b.onclick=()=>{const left=E.options(state).filter(a=>a.ttl&&!a.blocked).map(a=>a.label);if(left.length&&!confirm('还有可探索入口：'+left.join('、')+'。\\n进入第二轮后，这些入口将关闭。确定继续吗？'))return;commit(E.next(state),'已进入第二轮。第一轮探索入口已关闭。');};$('actions').append(b);}$('enter').disabled=!!E.reason(state,'g7p2');$('enter').textContent=state.step==='map'?(state.stamp<E.open?'幽寂谷 · 尚未开放':state.stamp>E.close?'幽寂谷 · 已过期':'幽寂谷 · 进入'):state.step==='done'?'幽寂谷 · 已结束':'幽寂谷 · 探索中';$('chat').hidden=['map','done'].includes(state.step);$('bag').replaceChildren();for(const item of state.inventory){const span=document.createElement('span');span.className='tag';span.textContent=item;$('bag').append(span);}if(!state.inventory.length)$('bag').textContent='行囊尚空';$('known').textContent=state.known.map_youjigu?'已知条件：已获得幽寂谷地图':'尚未取得地图条件';$('log').replaceChildren();for(const line of state.log){const li=document.createElement('li');li.textContent=line;$('log').append(li);}$('receipt').replaceChildren();if(state.receipt){const p=document.createElement('p');p.className='receipt';p.textContent=state.receipt.type+' · 世界时间推进 '+state.receipt.days+' 日（测试值）\\n'+E.date(state.receipt.from)+' → '+E.date(state.receipt.to)+'。获得：'+(state.receipt.rewards.join('、')||'无')+'。';$('receipt').append(p);}$('undo').disabled=!history.length;}
function choose(id){const a=E.defs[id];if(a.finish||a.early){const days=a.early?E.config.earlyDays:E.config.completeDays;if(!confirm('确定'+a.label+'吗？\\n这会结束整个幽寂谷事件，无法继续探索。\\n世界日期将推进'+days+'日（测试值）：'+E.date(state.stamp)+' → '+E.date(state.stamp+days)+'。\\n保留物品：'+(state.inventory.join('、')||'无')+'。'))return;}let message=a.label+'：已完成。';if(a.reward)message+='\\n获得：'+a.reward+'。';if(a.group)message+='\\n本组另一项已关闭，本次不能再次选择。';if(a.to==='first')message+='\\n已返回第一轮选择面板，仍可选择其它未过期入口。';if(a.finish||a.early)message+='\\n事件已结束，世界日期已按回执推进。';commit(E.act(state,id),message);}
$('enter').onclick=()=>choose('g7p2');$('talk').onclick=()=>{const r=E.talk(state,$('text').value);commit(r,'已记录一轮自由活动。世界时间未改变；未访问入口的剩余轮数减1。');if(r.ok)$('text').value='';};$('undo').onclick=()=>{if(history.length){state=history.pop();notice='已恢复上一步日期、条件、互斥和轮数。';persist();render();}};$('reset').onclick=()=>{const m=Number($('month').value),d=Number($('day').value);if(!Number.isInteger(m)||m<1||m>12||!Number.isInteger(d)||d<1||d>30){notice='请输入有效月份和日期';render();return;}state=E.initial($('identity').value,E.day(1578,m,d));history=[];notice='';persist();render();};$('export').onclick=()=>{const blob=new Blob([JSON.stringify({state,history},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='幽寂谷-试玩存档.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};render();
</script></html>'''
(out/'幽寂谷-点击试玩.html').write_text(html.replace('IMAGE',img).replace('ENGINE',engine))
