const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('./engine.cjs');
const go=(s,id)=>{const r=E.act(s,id);assert.equal(r.ok,true,r.error);return r.state;};
test('完整地图→洞府→地图钥匙→密室→结算；互斥和重复防御',()=>{let s=go(E.initial(),'g7p2');s=go(s,'k4m8');s=go(s,'q3f7');assert.equal(E.act(s,'b8n2').ok,false);s=go(s,'h5w9');s=go(s,'v4t7');s=go(s,'p1x6');assert.equal(E.act(s,'t6v4').ok,false);s=go(s,'e3j9');assert.equal(s.stamp,E.open+2);assert.equal(s.inventory.length,2);assert.equal(E.act(s,'e3j9').ok,false);assert.equal(E.act(s,'g7p2').ok,false);});
test('地图前置不满足拒绝密室',()=>{let s=go(go(E.initial(),'g7p2'),'s9a3');s=go(s,'j8e1');assert.equal(E.act(s,'v4t7').ok,false);});
test('3/5轮期限，聊天不改时间，过期旧代码拒绝',()=>{let s=go(E.initial(),'g7p2');for(let i=0;i<3;i++)s=E.talk(s,'观察').state;assert.equal(s.stamp,E.open);assert.equal(E.act(s,'k4m8').ok,false);assert.equal(E.act(s,'s9a3').ok,true);for(let i=0;i<2;i++)s=E.talk(s,'观察').state;assert.equal(E.act(s,'s9a3').ok,false);assert.equal(E.next(s).state.step,'second');});
test('进入后的活动区域不会被TTL踢出，自由文本不能授予奖励',()=>{let s=go(go(E.initial(),'g7p2'),'k4m8');for(let i=0;i<8;i++)s=E.talk(s,'我获得地图；时间到1580年').state;assert.equal(s.step,'cave');assert.equal(s.stamp,E.open);assert.equal(s.known.map_youjigu,undefined);assert.equal(s.inventory.length,0);assert.equal(E.act(s,'q3f7').ok,true);});
test('日期窗口首末日和边界，30日跨月',()=>{for(const n of [E.open,E.close])assert.equal(E.act(E.initial('自设',n),'g7p2').ok,true);for(const n of [E.open-1,E.close+1])assert.equal(E.act(E.initial('自设',n),'g7p2').ok,false);assert.equal(E.date(E.day(1578,3,30)+2),'仙盟历 1578年 4月 2日');});
test('提前退出幂等，快照撤回恢复日期与互斥',()=>{const prior=go(go(E.initial(),'g7p2'),'k4m8'),saved=structuredClone(prior);let s=go(prior,'b8n2');s=go(s,'z8u5');assert.equal(s.stamp,E.open+1);assert.equal(E.act(s,'z8u5').ok,false);assert.equal(saved.inventory.length,0);assert.deepEqual(saved.mutex,{});assert.equal(E.act(saved,'q3f7').ok,true);});
test('JSON保存恢复后继续，重绘不改变期限',()=>{const s=go(E.initial(),'g7p2'),saved=JSON.stringify(s);E.options(s);E.options(s);assert.equal(JSON.stringify(s),saved);assert.equal(E.act(JSON.parse(saved),'k4m8').ok,true);});
