const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/engine-test.js'),create=require('../src/controller.cjs'),runtime=require('../src/runtime-test.js');
function setup(){const ctx={chatId:'A',chat:[{mes:'开场',is_user:false}]},layers={chat:{},messages:[{}]},service=runtime({});const api={context:()=>ctx,getVariables:o=>structuredClone(o.type==='chat'?layers.chat:layers.messages[o.message_id]||{}),updateVariablesWith:(f,o)=>{if(o.type==='chat')layers.chat=f(layers.chat);else layers.messages[o.message_id]=f(layers.messages[o.message_id]||{});}};const c=create(E,{context:()=>ctx,capture:()=>service.capture(api),snapshot:t=>service.snapshot(api,t),getVariables:api.getVariables,guard:()=>{},transact:b=>service.transact(api,b)});const read=async()=> (await c.read()).saved;async function reply(id,body,outcome='success'){ctx.chat.push({mes:id==='next'?'继续深入幽寂谷':E.defs[id].label,is_user:true});layers.messages.push({});ctx.chat.push({mes:body+`<Youjigu_result id="${id}" outcome="${outcome}"/>`,is_user:false});layers.messages.push({});return c.mutate({type:'story',id:ctx.chat.length-1});}async function action(id,body){await c.mutate({type:'action',id});return reply(id,body);}return {ctx,layers,c,read,reply,action};}
async function start(x){await x.c.mutate({type:'start',identity:'自设',month:3,day:1});}
test('入口点击只登记待行动，发出玩家消息后有效故事楼才开放下一步',async()=>{const x=setup();await start(x);await x.c.mutate({type:'action',id:'g7p2'});assert.equal((await x.read()).state.step,'map');assert.equal((await x.read()).pending.id,'g7p2');await assert.rejects(x.c.mutate({type:'action',id:'k4m8'}),/尚未完成/);await x.reply('g7p2','你沿溪水进入谷口。');assert.equal((await x.read()).state.step,'first');await x.c.mutate({type:'action',id:'k4m8'});assert.equal((await x.read()).state.step,'first');await x.reply('k4m8','你穿过石门进入洞府。');assert.equal((await x.read()).state.step,'cave');});
test('没有新玩家楼的助手文字不能完成已选节点',async()=>{const x=setup();await start(x);await x.c.mutate({type:'action',id:'g7p2'});x.ctx.chat.push({mes:'你进入谷口。'});x.layers.messages.push({});await x.c.mutate({type:'story',id:1});assert.equal((await x.read()).state.step,'map');assert.equal((await x.read()).pending.id,'g7p2');});
test('成功标记缺失仍能在真实行动故事楼完成；明确失败不推进',async()=>{for(const outcome of ['','<Youjigu_result id="g7p2" outcome="failure"/>']){const x=setup();await start(x);await x.c.mutate({type:'action',id:'g7p2'});x.ctx.chat.push({mes:'进入幽寂谷',is_user:true},{mes:'你循溪而行。'+outcome});x.layers.messages.push({},{});await x.c.mutate({type:'story',id:2});assert.equal((await x.read()).state.step,outcome?'map':'first');assert.equal((await x.read()).pending,null);}});
test('授权暗格实际取得地图后授予known，互斥另一项不可用',async()=>{const x=setup();await start(x);await x.action('g7p2','你进入谷口。');await x.action('k4m8','你进入洞府。');await x.c.mutate({type:'action',id:'q3f7'});assert.deepEqual((await x.read()).state.inventory,[]);await x.reply('q3f7','你打开铁匣，取出地图，收入行囊。');assert.equal((await x.read()).state.known.map_youjigu,true);await assert.rejects(x.c.mutate({type:'action',id:'b8n2'}),/互斥/);});
test('计划/否定/旁观/铁匣不能替代奖励，但已选择的互斥组不重新开放',async()=>{for(const body of ['你打算取得地图。','你未能取得地图。','你看见别人获得地图。','你取得一个铁匣。']){const x=setup();await start(x);await x.action('g7p2','谷口。');await x.action('k4m8','洞府。');await x.action('q3f7',body);assert.equal((await x.read()).state.known.map_youjigu,undefined);assert.equal((await x.read()).pending,null);assert.ok(!E.options((await x.read()).state).some(a=>a.id==='q3f7'||a.id==='b8n2'));assert.ok(E.options((await x.read()).state).some(a=>a.id==='h5w9'));assert.equal((await x.read()).state.mutex.cave,'q3f7');}});
test('自由对话不授未选奖励、世界时间不变、同楼不重复计轮',async()=>{const x=setup();await start(x);await x.action('g7p2','进入谷口。');x.ctx.chat.push({mes:'你取得地图。'});x.layers.messages.push({});await x.c.mutate({type:'story',id:3});await x.c.mutate({type:'story',id:3});const s=(await x.read()).state;assert.equal(s.turn,2);assert.equal(s.stamp,E.open);assert.deepEqual(s.inventory,[]);});
test('继续深入同样必须等新故事楼，不能点击直接开放山谷和密室',async()=>{const x=setup();await start(x);await x.action('g7p2','谷口。');await x.c.mutate({type:'next',confirm:true});assert.equal((await x.read()).state.step,'first');assert.equal((await x.read()).pending.id,'next');await x.reply('next','你沿小径来到谷中岔路。');assert.equal((await x.read()).state.step,'second');});
test('退出确认后也只登记，完成退出故事楼才唯一结算，重复回调不加时',async()=>{const x=setup();await start(x);await x.action('g7p2','谷口。');await assert.rejects(x.c.mutate({type:'action',id:'z8u5'}),/明确确认/);await x.c.mutate({type:'action',id:'z8u5',confirm:true});assert.equal((await x.read()).state.stamp,E.open);assert.ok(x.c.prompt((await x.read()).state,(await x.read()).pending).includes(E.date(E.open+1)));await x.reply('z8u5','你沿山路离开幽寂谷。');await x.c.mutate({type:'story',id:x.ctx.chat.length-1});assert.equal((await x.read()).state.stamp,E.open+1);assert.equal((await x.read()).state.step,'done');});
test('删除行动回复恢复等待和旧地点，重新回复重新完成',async()=>{const x=setup();await start(x);await x.c.mutate({type:'action',id:'g7p2'});await x.reply('g7p2','你来到谷口。');x.ctx.chat.splice(2);x.layers.messages.splice(2);await x.c.mutate({type:'restore'});assert.equal((await x.read()).state.step,'map');assert.equal((await x.read()).pending.id,'g7p2');});
test('导演指令限制单项行动且保留Status_block，不展开未来奖励',()=>{const x=setup(),s=E.initial();const p=x.c.prompt(s,{id:'g7p2',label:'进入幽寂谷'});assert.ok(p.includes('本轮只演绎这一项'));assert.ok(p.includes('Status_block'));assert.ok(!p.includes('法宝'));});

test('两种机关任选其一，选择时两项立即隐藏，不需要先匹配奖励正文',async()=>{for(const choice of ['q3f7','b8n2']){const x=setup();await start(x);await x.action('g7p2','进入谷口。');await x.action('k4m8','进入洞府。');await x.c.mutate({type:'action',id:choice});let saved=await x.read();assert.equal(saved.state.mutex.cave,choice);assert.equal(saved.state.inventory.length,0);assert.ok(!E.options(saved.state).some(a=>a.group==='cave'));assert.ok(E.options(saved.state).some(a=>a.id==='h5w9'));await x.reply(choice,'你观察了一阵。','failure');saved=await x.read();assert.equal(saved.state.mutex.cave,choice);assert.equal(saved.state.inventory.length,0);assert.ok(!E.options(saved.state).some(a=>a.group==='cave'));}});
test('取消尚未完成的选择可释放自己的预留，不发物品',async()=>{const x=setup();await start(x);await x.action('g7p2','谷口。');await x.action('k4m8','洞府。');await x.c.mutate({type:'action',id:'q3f7'});await x.c.mutate({type:'cancel'});assert.equal((await x.read()).state.mutex.cave,undefined);assert.equal((await x.read()).state.inventory.length,0);assert.ok(E.options((await x.read()).state).some(a=>a.id==='b8n2'));});
test('离开洞府和山涧均在同一回复转到第二轮，不额外发送继续深入',async()=>{for(const [enter,leave] of [['k4m8','h5w9'],['s9a3','j8e1']]){const x=setup();await start(x);await x.action('g7p2','谷口。');await x.action(enter,'你进入该处。');const before=(await x.read()).state.turn;await x.c.mutate({type:'action',id:leave});let saved=await x.read();assert.ok(['cave','stream'].includes(saved.state.step));assert.ok(x.c.prompt(saved.state,saved.pending).includes('在这一楼完成过渡'));await x.reply(leave,'你离开此处，沿路深入到谷中岔路。');saved=await x.read();assert.equal(saved.state.step,'second');assert.equal(saved.state.turn,before+1);assert.ok(E.options(saved.state).some(a=>a.id==='u9h3'));}});
