const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const out=path.join(__dirname,'../产物'),card=JSON.parse(fs.readFileSync(path.join(out,'幽寂谷状态栏地图测试卡.json'))),data=card.data||card;
test('独立名称/脚本/世界书，旧时钟与正式绑定为零',()=>{assert.equal(card.name,data.name);assert.equal(data.name,'幽寂谷状态栏地图测试卡');assert.equal(data.extensions.world,'幽寂谷状态栏地图测试世界书');assert.equal(data.character_book.entries.length,3);assert.equal(data.extensions.regex_scripts.length,2);assert.equal(data.extensions.tavern_helper.scripts.length,2);assert.ok(!data.extensions.tavern_helper.scripts[1].content.includes('createXsdDispatcher'));assert.ok(!data.first_mes.includes('IdentityMenu'));});
test('PNG两个载荷均逐字节等于独立JSON',()=>{const png=fs.readFileSync(path.join(out,'幽寂谷状态栏地图测试卡.png')),json=fs.readFileSync(path.join(out,'幽寂谷状态栏地图测试卡.json'));let offset=8,found=0;while(offset<png.length){const n=png.readUInt32BE(offset),type=png.toString('ascii',offset+4,offset+8);if(type==='tEXt'){const body=png.subarray(offset+8,offset+8+n),i=body.indexOf(0),key=body.subarray(0,i).toString();if(['chara','ccv3'].includes(key)){assert.ok(Buffer.from(body.subarray(i+1).toString(),'base64').equals(json));found++;}}offset+=n+12;}assert.equal(found,2);});
class El{constructor(tag){this.tag=tag;this.children=[];this.value='';this.hidden=false;this.disabled=false;this.style={};this.attrs={};}setAttribute(k,v){this.attrs[k]=v;}querySelector(q){return this.children.find(x=>q==='[data-youjigu-map]'?x.attrs?.['data-youjigu-map']:q==='[data-xds-panel]'?x.attrs?.['data-xds-panel']:q==='.xh-title'?x.className==='xh-title':false)||null;}appendChild(x){this.append(x);}append(...xs){this.children.push(...xs);}replaceChildren(){this.children=[];}remove(){this.removed=true;}dispatchEvent(){}focus(){} }
async function boot(name=data.name){const els={},document={head:new El('head'),body:new El('body'),createElement:t=>{const e=new El(t);e.ownerDocument=document;return e;},getElementById:id=>{if(id==='send_textarea')return els[id]??=new El('textarea');if(id==='send_but')return els[id]??=Object.assign(new El('button'),{click(){ctx.chat.push({mes:els.send_textarea.value,is_user:true});layers.messages.push({});sandbox.is_send_press=true;ctx.isGenerating=true;for(const f of listeners.sent||[])f();}});return [...document.body.children].find(e=>e.id===id)||null;}};let layers={chat:{},messages:[{}]},listeners={},prompts=[];const ctx={chatId:'test',chat:[{mes:data.first_mes}],characterId:0,characters:[{name}],event_types:{MESSAGE_SENT:'sent',MESSAGE_RECEIVED:'received',GENERATION_ENDED:'ended',CHAT_CHANGED:'changed',MESSAGE_SWIPED:'swiped',MESSAGE_DELETED:'deleted'},eventSource:{on:(n,f)=>(listeners[n]??=[]).push(f),removeListener:(n,f)=>listeners[n]=listeners[n]?.filter(x=>x!==f)},setExtensionPrompt:(...args)=>prompts.push(args)};let confirmed=true;const sandbox={document,console,structuredClone,Event:class{},setTimeout:f=>{Promise.resolve().then(f);return 1;},setInterval:()=>1,clearInterval:()=>{},confirm:()=>confirmed,SillyTavern:{getContext:()=>ctx},TavernHelper:{getVariables:o=>structuredClone(o.type==='chat'?layers.chat:layers.messages[o.message_id]||{}),updateVariablesWith:(f,o)=>{if(o.type==='chat')layers.chat=f(layers.chat);else layers.messages[o.message_id]=f(layers.messages[o.message_id]||{});}}};sandbox.window=sandbox;sandbox.parent=sandbox;sandbox.top=sandbox;vm.createContext(sandbox);vm.runInContext('window.Function=Function',sandbox);vm.runInContext(data.extensions.tavern_helper.scripts[1].content,sandbox);const settle=()=>new Promise(r=>setImmediate(r));await settle();return {sandbox,ctx,layers,listeners,prompts,document,settle,setConfirmed:v=>confirmed=v};}
function walk(n){return [n,...n.children.flatMap(walk)];}
function pin(x,id){return walk(x.document.getElementById('yj-map-dialog')).find(n=>n.attrs['data-yj-node']===id);}
function labels(x){return walk(x.document.getElementById('yj-map-dialog')).filter(n=>n.tag==='span').map(n=>n.textContent);}
async function openMap(x){const panel=x.document.createElement('div'),title=x.document.createElement('div');title.className='xh-title';panel.append(title);x.sandbox.__youjiguTest.bind(panel);title.children[0].onclick();await x.settle();return x.document.getElementById('yj-map-dialog');}
async function reply(x,body){x.ctx.chat.push({mes:body});x.layers.messages.push({});x.sandbox.is_send_press=false;x.ctx.isGenerating=false;for(const f of x.listeners.ended||[])f();await x.settle();await x.settle();}
test('入口点选自动填入并原生发送，原点消失，新回复前无后续点',async()=>{const x=await boot(),dialog=await openMap(x);assert.deepEqual(labels(x),['幽寂谷']);const selected=pin(x,'g7p2');await selected.onclick();assert.equal(x.document.getElementById('send_textarea').value,'进入幽寂谷');assert.equal(x.ctx.chat.length,2);assert.equal(x.ctx.chat[1].mes,'进入幽寂谷');assert.equal(dialog.hidden,true);assert.deepEqual(labels(x),[]);assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'map');await selected.onclick();assert.equal(x.ctx.chat.length,2);await reply(x,'你沿溪进入谷口。<Status_block><地点>幽寂谷·谷口</地点></Status_block>');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'first');assert.ok(labels(x).includes('洞府'));assert.ok(labels(x).includes('山涧'));assert.ok(!labels(x).includes('幽寂谷'));assert.equal(walk(dialog).filter(n=>['p','h2','input','select'].includes(n.tag)).length,0);});
test('洞府也需新回复，无法未推进一楼就点香炉暗格',async()=>{const x=await boot();await openMap(x);await pin(x,'g7p2').onclick();await reply(x,'你踏入幽寂谷。');await pin(x,'k4m8').onclick();assert.equal(x.ctx.chat.at(-1).mes,'探索洞府');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'first');assert.ok(!labels(x).includes('洞府'));assert.ok(!labels(x).includes('香炉'));assert.ok(!labels(x).includes('暗格'));assert.ok(pin(x,'s9a3').disabled);await reply(x,'你步入洞府，望见一座香炉和一处暗格。');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'cave');assert.ok(pin(x,'q3f7'));assert.ok(pin(x,'b8n2'));});
test('完整强制发送路线：入口→洞府→地图→离开即深入→密室→法宝→确认退出',async()=>{const x=await boot();await openMap(x);for(const [id,body] of [['g7p2','你走入谷口。'],['k4m8','你进入洞府。'],['q3f7','你从铁匣中取出地图，收入行囊。'],['h5w9','你离开洞府，沿路走入谷中岔路。'],['v4t7','你循地图进入密室。'],['p1x6','你从左侧暗格取出法宝，收入行囊。']]){const n=pin(x,id);assert.ok(n,id);await n.onclick();await reply(x,body);}assert.equal(pin(x,'t6v4'),undefined);const count=x.ctx.chat.length;x.setConfirmed(false);await pin(x,'e3j9').onclick();assert.equal(x.ctx.chat.length,count);assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'secret');x.setConfirmed(true);await pin(x,'e3j9').onclick();assert.equal(x.ctx.chat.length,count+1);assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'secret');await reply(x,'你带着收获走出密室，离开山谷。');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'done');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.stamp,x.sandbox.YoujiguTest.open+2);assert.equal(labels(x).length,0);});
test('发送按钮不可用时不登记动作、不移动、不消费入口',async()=>{const x=await boot();await openMap(x);x.document.getElementById('send_but').disabled=true;await pin(x,'g7p2').onclick();assert.equal(x.ctx.chat.length,1);assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].pending,undefined);assert.ok(pin(x,'g7p2'));});
test('窗口/TTL/地图钥匙继续筛选，地图不保留当前位置重复点',async()=>{const x=await boot(),E=x.sandbox.YoujiguTest,map=x.sandbox.__youjiguTest.mapNodes;assert.equal(map(E.initial('自设',E.close+1)).length,0);const s=E.initial();s.step='first';s.turn=3;assert.ok(!map(s).some(a=>a.id==='k4m8'));assert.ok(map(s).some(a=>a.id==='s9a3'));assert.ok(!map(s).some(a=>a.id==='here'));s.step='second';assert.ok(!map(s).some(a=>a.id==='v4t7'));s.known.map_youjigu=true;assert.ok(map(s).some(a=>a.id==='v4t7'));});
test('保留实际HUD与Status渲染正则，挂载地图钩子，无独立悬浮入口',()=>{const scripts=data.extensions.tavern_helper.scripts;const hud=scripts.find(s=>s.name==='状态栏面板');assert.ok(hud.content.includes('__youjiguTest'));assert.ok(hud.content.includes('function mount('));assert.ok(data.first_mes.includes('Status_block'));assert.ok(data.extensions.regex_scripts[0].replaceString.includes('hud.mount'));assert.ok(!scripts[1].content.includes("open.id='yj-map-button'"));for(const s of scripts)new vm.Script(s.content);});
test('正式卡中误加载测试脚本不创建地图/不写变量',async()=>{const x=await boot('仙姝堕');assert.equal(x.document.getElementById('yj-map-dialog'),null);assert.deepEqual(x.layers.chat,{});});

test('实际地图：暗格点选后香炉和暗格同时消失，奖励核验失败也不重新出现',async()=>{const x=await boot();await openMap(x);await pin(x,'g7p2').onclick();await reply(x,'你进入谷口。');await pin(x,'k4m8').onclick();await reply(x,'你走入洞府。');await pin(x,'q3f7').onclick();assert.equal(pin(x,'q3f7'),undefined);assert.equal(pin(x,'b8n2'),undefined);assert.ok(pin(x,'h5w9'));await reply(x,'你取出一个铁匣。');assert.equal(pin(x,'q3f7'),undefined);assert.equal(pin(x,'b8n2'),undefined);assert.ok(pin(x,'h5w9'));const count=x.ctx.chat.length;await pin(x,'h5w9').onclick();await reply(x,'你离开洞府，径直深入谷中。');assert.equal(x.ctx.chat.length,count+2);assert.ok(pin(x,'u9h3'));assert.equal(pin(x,'next'),undefined);assert.equal(pin(x,'v4t7'),undefined);});
