'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm'),zlib=require('node:zlib');
const dir=__dirname,repo=path.resolve(dir,'../..'),output=path.join(dir,'产物');fs.mkdirSync(output,{recursive:true});
const read=name=>fs.readFileSync(path.join(dir,'src',name),'utf8');
const runtime=read('runtime-test.js'),core=read('engine-test.js')+'\n'+read('controller.cjs');
const map=fs.readFileSync(path.join(repo,'AI交接/地图事件链模板/幽寂谷-v0.2/map.jpg')).toString('base64');
const install=`(function(h){let r=h;try{if(h.parent?.document)r=h.parent;}catch(_){}r.Function(${JSON.stringify(core)})();})(window);\n`;
const host=read('host.js').replace('MAP_DATA','data:image/jpeg;base64,'+map);
const content=runtime+'\n'+install+host;new vm.Script(content);
fs.writeFileSync(path.join(output,'幽寂谷地图接入测试脚本.js'),content);
const input=path.join(repo,'最新角色卡/仙姝堕.json'),card=JSON.parse(fs.readFileSync(input,'utf8')),original=structuredClone(card.data||card);
let hud=original.extensions.tavern_helper.scripts.find(s=>s.name==='状态栏面板');hud=structuredClone(hud);hud.enabled=true;const anchor='window.__xsdCorrection?.bindStatusEntry(container);';if(!hud.content.includes(anchor))throw Error('HUD挂载锚点不符');hud.content=hud.content.replace(anchor,"try{(window.parent?.__youjiguTest||window.__youjiguTest)?.bind(container);}catch(_){}");
const entry={id:0,keys:[],secondary_keys:[],comment:'地图接入测试边界',content:'这是独立的幽寂谷地图事件链接入试验。只根据脚本提供的当前步骤叙述，不自行改变世界日期，不凭自由对话授予物品或推进任务。正式奖励名称和退出耗时未定，测试值不代表正式设定。',constant:true,selective:false,insertion_order:0,enabled:true,position:'before_char',extensions:{prevent_recursion:true,exclude_recursion:true,selectiveLogic:0,scan_depth:1}};
const data={name:'幽寂谷状态栏地图测试卡',description:'南疆山水之间，幽寂谷有洞府、溪流与曲折的小径。自由活动与固定节点选择结合；在地图选择地点，进入后以对话探索与选择关键分支。以连续的仙侠故事回应玩家的探索与交谈，不编造宝物尊名或未知设定。',personality:'忠实遵守脚本当前步骤与结算回执。',scenario:'玩家行至幽寂谷，在洞府与溪水之间探索。日期、物品、互斥及轮数均由后台管理。',first_mes:'山风沿着溪水吹来，幽寂谷的入口隐在层叠山影之间。你暂驻谷外，眼前的小径沿水向深处延伸。\n\n<Status_block><时间>仙盟历1578年3月1日</时间><地点>幽寂谷外</地点><身份>自设</身份><情况>暂驻谷外</情况></Status_block>',mes_example:'',creator_notes:'独立接入测试 v0.7。正式GM/旧状态机不运行，保留原HUD并接入地图；本卡只用测试事件和同契约事务运行时。须在新聊天中试验。不要覆盖仙姝堕正式卡。',system_prompt:'按脚本提供的当前步骤演绎，角色不能知道尚未选择的分支或未取得物品。模型不计算世界时间、不自行发奖，不输出后台代码。',post_history_instructions:'以最新脚本事件导演指令为准，以自然的连续故事回应自由行动。每轮保留Status_block供原状态栏显示；隐藏结果标记依本次动作指令输出。不得擅自改变世界时间或取得未核实奖励。',tags:['地图接入测试','幽寂谷'],creator:'gpt · 测试版',character_version:'map-hud-test-0.7',alternate_greetings:[],group_only_greetings:[],extensions:{xsd_assets:original.extensions.xsd_assets,world:'幽寂谷状态栏地图测试世界书',tavern_helper:{scripts:[hud,{type:'script',enabled:true,name:'幽寂谷地图接入测试',id:'youjigu-map-test-script',content,info:'独立事件测试，不并入正式世界书',button:{enabled:false,buttons:[]},data:{}}]},regex_scripts:[structuredClone(original.extensions.regex_scripts.find(r=>r.scriptName==='仙姝墮·状态栏渲染')),{id:'youjigu-result-hide',scriptName:'幽寂谷结果标记隐藏',findRegex:'<Youjigu_result[^>]*\\/>',replaceString:'',trimStrings:[],placement:[2],disabled:false,markdownOnly:true,promptOnly:false,runOnEdit:true,substituteRegex:0}],depth_prompt:{prompt:'自然演绎当前步骤；每次回复末尾保留<Status_block><时间>脚本日期</时间><地点>当前地点</地点><身份>当前身份</身份><情况>当前情况</情况></Status_block>。若有待执行动作，按导演指令输出隐藏结果标记；禁止在正文谈论规则、脚本、步骤编号或测试。',depth:0,role:'system'}},character_book:{name:'幽寂谷状态栏地图测试世界书',entries:[entry,...original.character_book.entries.filter(e=>['文风','【设定】世界观总览'].includes(e.comment)).map((e,i)=>({...e,id:i+1,constant:true,enabled:true,extensions:{...e.extensions,prevent_recursion:true}}))]}};
// 同步v2/v3和兼容平面字段，防止导入选中旧顶层名或开场白。
for(const key of Object.keys(data)){card[key]=data[key];if(card.data)card.data[key]=data[key];}
card.creatorcomment=data.creator_notes;
const json=Buffer.from(JSON.stringify(card,null,2));fs.writeFileSync(path.join(output,data.name+'.json'),json);
const world={name:data.character_book.name,entries:{0:{uid:0,key:[],keysecondary:[],comment:entry.comment,content:entry.content,constant:true,selective:false,order:0,position:0,disable:false,preventRecursion:true,excludeRecursion:true,selectiveLogic:0,scanDepth:1}}};for(const [i,e]of data.character_book.entries.entries())if(i>0)world.entries[i]={...world.entries[0],uid:i,comment:e.comment,content:e.content,order:i};fs.writeFileSync(path.join(output,world.name+'.json'),JSON.stringify(world,null,2));
// 只替换PNG元数据，保留原PNG像素与其余块逐字节，不改图像。
const png=fs.readFileSync(path.join(repo,'最新角色卡/仙姝堕.png')),sig=png.subarray(0,8),chunks=[];if(!sig.equals(Buffer.from('89504e470d0a1a0a','hex')))throw Error('输入不是PNG');
let offset=8;while(offset<png.length){const size=png.readUInt32BE(offset),type=png.toString('ascii',offset+4,offset+8),chunk=png.subarray(offset,offset+size+12),body=chunk.subarray(8,-4);if(['tEXt','zTXt','iTXt'].includes(type)&&['chara','ccv3'].includes(body.toString('utf8').split('\0')[0])){}else if(type!=='IEND')chunks.push(chunk);offset+=size+12;}
function crc(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let i=0;i<8;i++)c=(c>>>1)^((c&1)?0xedb88320:0);}return (c^0xffffffff)>>>0;}
function chunk(type,body){const name=Buffer.from(type),n=Buffer.alloc(4),c=Buffer.alloc(4);n.writeUInt32BE(body.length);c.writeUInt32BE(crc(Buffer.concat([name,body])));return Buffer.concat([n,name,body,c]);}
for(const key of ['chara','ccv3'])chunks.push(chunk('tEXt',Buffer.from(key+'\0'+json.toString('base64'))));chunks.push(chunk('IEND',Buffer.alloc(0)));fs.writeFileSync(path.join(output,data.name+'.png'),Buffer.concat([sig,...chunks]));
const hashes={input:{path:'最新角色卡/仙姝堕.json',sha256:crypto.createHash('sha256').update(fs.readFileSync(input)).digest('hex')},files:{}};for(const name of fs.readdirSync(output)){if(name==='SHA256.json')continue;const b=fs.readFileSync(path.join(output,name));hashes.files[name]={bytes:b.length,sha256:crypto.createHash('sha256').update(b).digest('hex')};}fs.writeFileSync(path.join(output,'SHA256.json'),JSON.stringify(hashes,null,2));console.log(JSON.stringify(hashes,null,2));
