const {test}=require('node:test'),assert=require('node:assert/strict');
const E=require('../src/engine-test.js'),create=require('../src/controller.cjs'),runtime=require('../src/runtime-test.js');
function setup(){const ctx={chatId:'test-A',chat:[{mes:'测试开场',is_user:false}]},layers={chat:{},messages:[{}]},service=runtime({}),fail={message:false};const api={context:()=>ctx,getVariables:async o=>structuredClone(o.type==='chat'?layers.chat:layers.messages[o.message_id]||{}),updateVariablesWith:(f,o)=>{if(fail.message&&o.type==='message')throw Error('message write blocked');if(o.type==='chat')layers.chat=f(layers.chat);else layers.messages[o.message_id]=f(layers.messages[o.message_id]||{});}};const guard=(t,s)=>{assert.equal(ctx.chatId,t.chatId);assert.equal(ctx.chat.length-1,t.messageId);if(s)assert.deepEqual(c.fingerprint(ctx.chat),s);};const c=create(E,{context:()=>ctx,capture:()=>service.capture(api),snapshot:t=>service.snapshot(api,t),getVariables:api.getVariables,guard,transact:build=>service.transact(api,build)});const start=()=>c.mutate({type:'start',identity:'自设',month:3,day:1}),action=(id,confirm=true)=>c.mutate({type:'action',id,confirm});function add(mes,is_user=false){ctx.chat.push({mes,is_user});layers.messages.push({});}return {ctx,layers,service,c,start,action,add,fail};}
test('真实统一队列/双层写读，完整点击链和退出确认',async()=>{const x=setup();await x.start();await x.action('g7p2');await x.action('k4m8');await x.action('q3f7');await x.action('h5w9');assert.equal((await x.c.read()).saved.state.step,'first');await x.c.mutate({type:'next',confirm:true});await x.action('v4t7');await x.action('p1x6');await assert.rejects(x.action('e3j9',false),/确认/);await x.action('e3j9');assert.equal((await x.c.read()).saved.state.stamp,E.open+2);assert.deepEqual(x.layers.chat.stat_data,x.layers.messages[0].stat_data);await assert.rejects(x.action('e3j9'),/不匹配/);});
test('有效故事自动计轮，重复事件不计，玩家和空回复不计，日期不变',async()=>{const x=setup();await x.start();await x.action('g7p2');x.add('观察',true);await assert.rejects(x.c.mutate({type:'story',id:1}),/有效/);x.add('溪边风声');await x.c.mutate({type:'story',id:2});await x.c.mutate({type:'story',id:2});let s=(await x.c.read()).saved.state;assert.equal(s.turn,1);assert.equal(s.stamp,E.open);x.add('');await assert.rejects(x.c.mutate({type:'story',id:3}),/有效/);});
test('同楼重生成撤自身动作/奖励，再计仍只一轮；删楼恢复历史日期',async()=>{const x=setup();await x.start();await x.action('g7p2');x.add('探索描述');await x.c.mutate({type:'story',id:1});await x.action('k4m8');await x.action('q3f7');x.ctx.chat[1].mes='重新生成的不同叙事';await x.c.mutate({type:'story',id:1});let s=(await x.c.read()).saved.state;assert.equal(s.turn,1);assert.equal(s.known.map_youjigu,undefined);assert.deepEqual(s.inventory,[]);await x.action('z8u5');assert.equal((await x.c.read()).saved.state.stamp,E.open+1);x.ctx.chat.pop();x.layers.messages.pop();await x.c.mutate({type:'restore'});s=(await x.c.read()).saved.state;assert.equal(s.stamp,E.open);assert.equal(s.turn,0);assert.equal(x.layers.chat.stat_data.仙盟历文,'1578年3月1日');});
test('旧面板revision被拒，并发重复奖励只发一次',async()=>{const x=setup();await x.start();const revision=(await x.c.read()).saved.revision;await x.action('g7p2');await assert.rejects(x.c.mutate({type:'action',id:'k4m8',revision}),/过期/);await x.action('k4m8');const r=await Promise.allSettled([x.action('q3f7'),x.action('q3f7')]);assert.equal(r.filter(v=>v.status==='fulfilled').length,1);assert.equal((await x.c.read()).saved.state.inventory.length,1);});
test('双层写失败不假报成功，重试不重复结算',async()=>{const x=setup();await x.start();await x.action('g7p2');x.fail.message=true;await assert.rejects(x.action('z8u5'),/blocked/);x.fail.message=false;assert.equal((await x.c.read()).saved.state.stamp,E.open);await x.action('z8u5');assert.equal((await x.c.read()).saved.state.stamp,E.open+1);});
test('持久变量读取恢复无需localStorage，切聊天隔离',async()=>{const x=setup();await x.start();await x.action('g7p2');await x.action('s9a3');const saved=(await x.c.read()).saved;assert.equal(saved.state.step,'stream');x.ctx.chatId='test-B';x.ctx.chat=[{mes:'另一局开场'}];x.layers.messages=[{}];assert.equal((await x.c.read()).saved,null);});
