const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const out=path.join(__dirname,'../产物'),card=JSON.parse(fs.readFileSync(path.join(out,'幽寂谷地图接入测试卡.json'))),data=card.data||card;
test('独立名称/脚本/世界书，旧时钟与正式绑定为零',()=>{assert.equal(card.name,data.name);assert.equal(data.name,'幽寂谷地图接入测试卡');assert.equal(data.extensions.world,'幽寂谷地图接入测试世界书');assert.equal(data.character_book.entries.length,1);assert.equal(data.extensions.regex_scripts.length,0);assert.equal(data.extensions.tavern_helper.scripts.length,1);assert.ok(!data.extensions.tavern_helper.scripts[0].content.includes('createXsdDispatcher'));assert.ok(!data.first_mes.includes('IdentityMenu'));});
test('PNG两个载荷均逐字节等于独立JSON',()=>{const png=fs.readFileSync(path.join(out,'幽寂谷地图接入测试卡.png')),json=fs.readFileSync(path.join(out,'幽寂谷地图接入测试卡.json'));let offset=8,found=0;while(offset<png.length){const n=png.readUInt32BE(offset),type=png.toString('ascii',offset+4,offset+8);if(type==='tEXt'){const body=png.subarray(offset+8,offset+8+n),i=body.indexOf(0),key=body.subarray(0,i).toString();if(['chara','ccv3'].includes(key)){assert.ok(Buffer.from(body.subarray(i+1).toString(),'base64').equals(json));found++;}}offset+=n+12;}assert.equal(found,2);});
class El{constructor(tag){this.tag=tag;this.children=[];this.value='';this.hidden=false;this.disabled=false;this.style={};}append(...xs){this.children.push(...xs);}replaceChildren(){this.children=[];}remove(){this.removed=true;}dispatchEvent(){}focus(){} }
async function boot(name=data.name){const els={},document={head:new El('head'),body:new El('body'),createElement:t=>new El(t),getElementById:id=>{if(id==='send_textarea')return els[id]??=new El('textarea');return [...document.body.children].find(e=>e.id===id)||null;}};let layers={chat:{},messages:[{}]},listeners={},prompts=[];const ctx={chatId:'test',chat:[{mes:data.first_mes}],characterId:0,characters:[{name}],event_types:{MESSAGE_RECEIVED:'received',GENERATION_ENDED:'ended',CHAT_CHANGED:'changed',MESSAGE_SWIPED:'swiped',MESSAGE_DELETED:'deleted'},eventSource:{on:(n,f)=>(listeners[n]??=[]).push(f),removeListener:(n,f)=>listeners[n]=listeners[n]?.filter(x=>x!==f)},setExtensionPrompt:(...args)=>prompts.push(args)};let confirmed=true;const sandbox={document,console,structuredClone,Event:class{},setTimeout:f=>{Promise.resolve().then(f);return 1;},setInterval:()=>1,clearInterval:()=>{},confirm:()=>confirmed,SillyTavern:{getContext:()=>ctx},TavernHelper:{getVariables:o=>structuredClone(o.type==='chat'?layers.chat:layers.messages[o.message_id]||{}),updateVariablesWith:(f,o)=>{if(o.type==='chat')layers.chat=f(layers.chat);else layers.messages[o.message_id]=f(layers.messages[o.message_id]||{});}}};sandbox.window=sandbox;sandbox.parent=sandbox;sandbox.top=sandbox;vm.createContext(sandbox);vm.runInContext('window.Function=Function',sandbox);vm.runInContext(data.extensions.tavern_helper.scripts[0].content,sandbox);const settle=()=>new Promise(r=>setImmediate(r));await settle();return {sandbox,ctx,layers,listeners,prompts,document,settle,setConfirmed:v=>confirmed=v};}
function walk(n){return [n,...n.children.flatMap(walk)];}
test('真实卡内脚本+页面回调：启动/进入/回复计轮/确认退出/切卡清理',async()=>{const x=await boot();const dialog=x.document.getElementById('yj-map-dialog');const click=async label=>{const b=walk(dialog).find(n=>n.tag==='button'&&n.textContent.startsWith(label));assert.ok(b,label);assert.equal(b.disabled,false);await b.onclick();await x.settle();};await click('确认身份和测试日期');await click('进入幽寂谷');await click('探索山涧');x.ctx.chat.push({mes:'溪水缓缓流过谷底。',is_user:false});x.layers.messages.push({});for(const f of x.listeners.received)f(1);await x.settle();await x.settle();const read=()=>x.layers.chat.stat_data.youjigu_map_test[0].state;assert.equal(read().turn,1);await click('离开山涧');assert.equal(read().step,'first');assert.ok(walk(dialog).some(n=>n.textContent?.startsWith('探索洞府')));x.setConfirmed(false);await click('提前离开幽寂谷');assert.equal(read().step,'first');x.setConfirmed(true);await click('提前离开幽寂谷');assert.equal(read().step,'done');assert.equal(read().stamp,1578*360+60+1);assert.ok(x.prompts.some(p=>p[1].includes('仅根据真实回执')));x.ctx.characters[0].name='仙姝堕';await x.sandbox.__youjiguTest.refresh();assert.ok(dialog.removed);assert.equal(x.prompts.at(-1)[1],'');});
test('正式卡中误加载测试脚本不创建地图/不写变量',async()=>{const x=await boot('仙姝堕');assert.equal(x.document.getElementById('yj-map-dialog'),null);assert.deepEqual(x.layers.chat,{});});
