const {test}=require('node:test'),assert=require('node:assert/strict'),E=require('../src/engine-test.js'),create=require('../src/controller.cjs'),runtime=require('../src/runtime-test.js');
function setup(){const ctx={chatId:'A',chat:[{mes:'开场',is_user:false}]},layers={chat:{},messages:[{}]},service=runtime({});const api={context:()=>ctx,getVariables:o=>structuredClone(o.type==='chat'?layers.chat:layers.messages[o.message_id]||{}),updateVariablesWith:(f,o)=>{if(o.type==='chat')layers.chat=f(layers.chat);else layers.messages[o.message_id]=f(layers.messages[o.message_id]||{});}};const c=create(E,{context:()=>ctx,capture:()=>service.capture(api),snapshot:t=>service.snapshot(api,t),getVariables:api.getVariables,guard:()=>{},transact:b=>service.transact(api,b)});const read=async()=> (await c.read()).saved;async function reply(id,body,outcome='success'){ctx.chat.push({mes:E.defs[id].label,is_user:true});layers.messages.push({});ctx.chat.push({mes:body+`<Youjigu_result id="${id}" outcome="${outcome}"/>`,is_user:false});layers.messages.push({});return c.mutate({type:'story',id:ctx.chat.length-1});}async function action(id,body){await c.mutate({type:'action',id});return reply(id,body);}return {ctx,layers,c,read,reply,action};}
test('LLM参与后才进入地点，点击不改变步骤',async()=>{const x=setup();await x.c.mutate({type:'start',identity:'自设',month:3,day:1});await x.c.mutate({type:'action',id:'g7p2'});assert.equal((await x.read()).state.step,'map');assert.ok((await x.read()).pending);await x.reply('g7p2','你循溪进入谷口。');assert.equal((await x.read()).state.step,'first');});
test('实际正文+匹配动作标记后发奖，互斥后端拒绝',async()=>{const x=setup();await x.c.mutate({type:'start',identity:'自设',month:3,day:1});await x.action('g7p2','进入谷口。');await x.action('k4m8','你步入洞府。');await x.c.mutate({type:'action',id:'q3f7'});assert.deepEqual((await x.read()).state.inventory,[]);await x.reply('q3f7','你打开暗格，取出一张地图。');assert.equal((await x.read()).state.known.map_youjigu,true);await assert.rejects(x.c.mutate({type:'action',id:'b8n2'}),/互斥/);});
test('计划/否定/没有正文证据，即使success标记也不授奖',async()=>{for(const text of ['你打算取得地图。','你未能找到地图。','暗格中空空如也。','你看见别人取得地图。','你发现暗格中有地图，但没有拿走。']){const x=setup();await x.c.mutate({type:'start',identity:'自设',month:3,day:1});await x.action('g7p2','进入谷口。');await x.action('k4m8','进入洞府。');await x.action('q3f7',text);assert.deepEqual((await x.read()).state.inventory,[]);assert.equal((await x.read()).state.known.map_youjigu,undefined);}});
test('待叙事期间不能跳节点，取消不发奖',async()=>{const x=setup();await x.c.mutate({type:'start',identity:'自设',month:3,day:1});await x.c.mutate({type:'action',id:'g7p2'});await assert.rejects(x.c.mutate({type:'action',id:'k4m8'}),/等待/);await x.c.mutate({type:'cancel'});assert.equal((await x.read()).pending,null);assert.equal((await x.read()).state.step,'map');});
test('自由故事不发奖不加时，重复事件只计一次',async()=>{const x=setup();await x.c.mutate({type:'start',identity:'自设',month:3,day:1});await x.action('g7p2','进入谷口。');x.ctx.chat.push({mes:'你在溪边自由散步，并声称已获得地图。'});x.layers.messages.push({});await x.c.mutate({type:'story',id:3});await x.c.mutate({type:'story',id:3});const s=(await x.read()).state;assert.equal(s.turn,2);assert.equal(s.stamp,E.open);assert.deepEqual(s.inventory,[]);});
test('删楼恢复此前步骤和奖励，确认退出才加时',async()=>{const x=setup();await x.c.mutate({type:'start',identity:'自设',month:3,day:1});await x.action('g7p2','进入谷口。');await assert.rejects(x.c.mutate({type:'action',id:'z8u5'}),/确认/);await x.c.mutate({type:'action',id:'z8u5',confirm:true});assert.equal((await x.read()).state.stamp,E.open+1);x.ctx.chat.splice(1);x.layers.messages.splice(1);await x.c.mutate({type:'restore'});assert.equal((await x.read()).state.stamp,E.open);});
test('当前步骤提示包含场景与隐藏结果格式，不包含未来整棵剧情树',()=>{const x=setup(),s=E.initial();s.step='stream';const p=x.c.prompt(s);assert.ok(p.includes('溪水'));assert.ok(!p.includes('左右各有暗格'));assert.ok(p.includes('Status_block'));});
