const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const out=path.join(__dirname,'../产物'),card=JSON.parse(fs.readFileSync(path.join(out,'幽寂谷状态栏地图测试卡.json'))),data=card.data||card;
test('独立名称/脚本/世界书，旧时钟与正式绑定为零',()=>{assert.equal(card.name,data.name);assert.equal(data.name,'幽寂谷状态栏地图测试卡');assert.equal(data.extensions.world,'幽寂谷状态栏地图测试世界书');assert.equal(data.character_book.entries.length,3);assert.equal(data.extensions.regex_scripts.length,2);assert.equal(data.extensions.tavern_helper.scripts.length,2);assert.ok(!data.extensions.tavern_helper.scripts[1].content.includes('createXsdDispatcher'));assert.ok(!data.first_mes.includes('IdentityMenu'));});
test('PNG两个载荷均逐字节等于独立JSON',()=>{const png=fs.readFileSync(path.join(out,'幽寂谷状态栏地图测试卡.png')),json=fs.readFileSync(path.join(out,'幽寂谷状态栏地图测试卡.json'));let offset=8,found=0;while(offset<png.length){const n=png.readUInt32BE(offset),type=png.toString('ascii',offset+4,offset+8);if(type==='tEXt'){const body=png.subarray(offset+8,offset+8+n),i=body.indexOf(0),key=body.subarray(0,i).toString();if(['chara','ccv3'].includes(key)){assert.ok(Buffer.from(body.subarray(i+1).toString(),'base64').equals(json));found++;}}offset+=n+12;}assert.equal(found,2);});
class El{constructor(tag){this.tag=tag;this.children=[];this.value='';this.hidden=false;this.disabled=false;this.style={};this.attrs={};}setAttribute(k,v){this.attrs[k]=v;}querySelector(q){return this.children.find(x=>q==='[data-youjigu-map]'?x.attrs?.['data-youjigu-map']:q==='[data-xds-panel]'?x.attrs?.['data-xds-panel']:q==='.xh-title'?x.className==='xh-title':false)||null;}appendChild(x){this.append(x);}append(...xs){this.children.push(...xs);}replaceChildren(){this.children=[];}remove(){this.removed=true;}dispatchEvent(){}focus(){} }
async function boot(name=data.name){const els={},document={head:new El('head'),body:new El('body'),createElement:t=>{const e=new El(t);e.ownerDocument=document;return e;},getElementById:id=>{if(id==='send_textarea')return els[id]??=new El('textarea');return [...document.body.children].find(e=>e.id===id)||null;}};let layers={chat:{},messages:[{}]},listeners={},prompts=[];const ctx={chatId:'test',chat:[{mes:data.first_mes}],characterId:0,characters:[{name}],event_types:{MESSAGE_SENT:'sent',MESSAGE_RECEIVED:'received',GENERATION_ENDED:'ended',CHAT_CHANGED:'changed',MESSAGE_SWIPED:'swiped',MESSAGE_DELETED:'deleted'},eventSource:{on:(n,f)=>(listeners[n]??=[]).push(f),removeListener:(n,f)=>listeners[n]=listeners[n]?.filter(x=>x!==f)},setExtensionPrompt:(...args)=>prompts.push(args)};let confirmed=true;const sandbox={document,console,structuredClone,Event:class{},setTimeout:f=>{Promise.resolve().then(f);return 1;},setInterval:()=>1,clearInterval:()=>{},confirm:()=>confirmed,SillyTavern:{getContext:()=>ctx},TavernHelper:{getVariables:o=>structuredClone(o.type==='chat'?layers.chat:layers.messages[o.message_id]||{}),updateVariablesWith:(f,o)=>{if(o.type==='chat')layers.chat=f(layers.chat);else layers.messages[o.message_id]=f(layers.messages[o.message_id]||{});}}};sandbox.window=sandbox;sandbox.parent=sandbox;sandbox.top=sandbox;vm.createContext(sandbox);vm.runInContext('window.Function=Function',sandbox);vm.runInContext(data.extensions.tavern_helper.scripts[1].content,sandbox);const settle=()=>new Promise(r=>setImmediate(r));await settle();return {sandbox,ctx,layers,listeners,prompts,document,settle,setConfirmed:v=>confirmed=v};}
function walk(n){return [n,...n.children.flatMap(walk)];}
function pin(x,id){return walk(x.document.getElementById('yj-map-dialog')).find(n=>n.attrs['data-yj-node']===id);}
function labels(x){return walk(x.document.getElementById('yj-map-dialog')).filter(n=>n.tag==='span').map(n=>n.textContent);}
async function openMap(x){const panel=x.document.createElement('div'),title=x.document.createElement('div');title.className='xh-title';panel.append(title);x.sandbox.__youjiguTest.bind(panel);await title.children[0].onclick();await x.settle();return x.document.getElementById('yj-map-dialog');}
async function reply(x,user,body){x.ctx.chat.push({mes:user,is_user:true},{mes:body});x.layers.messages.push({},{});for(const f of x.listeners.ended||[])await f();await x.settle();await x.settle();}
test('首次地图只有幽寂谷，点击不收起不空白，立即出现洞府山涧和当前圆点',async()=>{const x=await boot(),dialog=await openMap(x);assert.deepEqual(labels(x),['幽寂谷']);await pin(x,'g7p2').onclick();await x.settle();assert.equal(dialog.hidden,false);assert.ok(labels(x).includes('幽寂谷'));assert.ok(labels(x).includes('洞府'));assert.ok(labels(x).includes('山涧'));assert.equal(pin(x,'here').attrs['aria-current'],'location');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.identity,'自设');assert.equal(walk(dialog).filter(n=>['select','input','h2','p'].includes(n.tag)).length,0);await reply(x,'进入幽寂谷','你沿着溪流走进谷口。');await x.sandbox.__youjiguTest.refresh();assert.ok(pin(x,'k4m8'));assert.ok(pin(x,'s9a3'));});
test('整条地图路线：洞府→暗格拿地图→谷口→谷中岔路→密室→奖励→确认退出',async()=>{const x=await boot(),dialog=await openMap(x);await pin(x,'g7p2').onclick();await reply(x,'进入幽寂谷','你踏入谷口。');await pin(x,'k4m8').onclick();assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'cave');assert.deepEqual(new Set(labels(x)),new Set(['洞府','香炉','暗格','谷口','离谷']));await reply(x,'探索洞府','你走进洞府，香炉与暗格映入眼帘。');await pin(x,'q3f7').onclick();await reply(x,'开启暗格','你从铁匣里取出幽寂谷地图，收入行囊。');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.known.map_youjigu,true);assert.equal(pin(x,'b8n2'),undefined);assert.equal(pin(x,'q3f7'),undefined);await pin(x,'h5w9').onclick();await reply(x,'离开洞府','你返回谷口。');assert.ok(pin(x,'s9a3'));await pin(x,'next').onclick();assert.ok(pin(x,'v4t7'));await pin(x,'v4t7').onclick();await reply(x,'前往密室','你循地图进入密室。');assert.ok(pin(x,'p1x6'));assert.ok(pin(x,'t6v4'));await pin(x,'p1x6').onclick();await reply(x,'打开左边暗格','你从左侧暗格取出法宝，收入行囊。');assert.equal(pin(x,'t6v4'),undefined);x.setConfirmed(false);await pin(x,'e3j9').onclick();assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'secret');x.setConfirmed(true);await pin(x,'e3j9').onclick();assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'done');assert.equal(walk(dialog).filter(n=>n.tag==='button').length,0);assert.equal(walk(dialog).filter(n=>n.tag==='img').length,1);});
test('时间与TTL/known筛选地图节点，未取得地图不泄露密室',async()=>{const x=await boot();const E=x.sandbox.YoujiguTest,map=x.sandbox.__youjiguTest.mapNodes;let s=E.initial('自设',E.close+1);assert.equal(map(s).length,0);s=E.initial();s.step='first';s.turn=3;assert.ok(!map(s).some(a=>a.id==='k4m8'));assert.ok(map(s).some(a=>a.id==='s9a3'));s.turn=5;assert.ok(!map(s).some(a=>a.id==='s9a3'));assert.ok(map(s).some(a=>a.id==='here'));assert.ok(map(s).some(a=>a.id==='next'));s.step='second';assert.ok(!map(s).some(a=>a.id==='v4t7'));s.known.map_youjigu=true;assert.ok(map(s).some(a=>a.id==='v4t7'));});
test('自然对话地点选择立即接入地图，不依赖模型回执',async()=>{const x=await boot();await x.sandbox.__youjiguTest.controller.mutate({type:'action',id:'g7p2'});x.ctx.chat.push({mes:'探索洞府',is_user:true});x.layers.messages.push({});for(const f of x.listeners.sent||[])await f();assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].state.step,'cave');assert.equal(x.layers.chat.stat_data.youjigu_map_test[0].pending,undefined);assert.ok(labels(x).includes('暗格'));assert.ok(x.prompts.at(-1)[1].includes('洞府内'));});
test('保留实际HUD与Status渲染正则，挂载地图钩子，无独立悬浮入口',()=>{const scripts=data.extensions.tavern_helper.scripts;const hud=scripts.find(s=>s.name==='状态栏面板');assert.ok(hud.content.includes('__youjiguTest'));assert.ok(hud.content.includes('function mount('));assert.ok(data.first_mes.includes('Status_block'));assert.ok(data.extensions.regex_scripts[0].replaceString.includes('hud.mount'));assert.ok(!scripts[1].content.includes("open.id='yj-map-button'"));for(const s of scripts)new vm.Script(s.content);});
test('正式卡中误加载测试脚本不创建地图/不写变量',async()=>{const x=await boot('仙姝堕');assert.equal(x.document.getElementById('yj-map-dialog'),null);assert.deepEqual(x.layers.chat,{});});
